/* ATK views — shared renderer for OKX Agent Trade Kit inline views. Loaded from a CDN; widgets stream data only. */
(function(){
const CSS=`
:root{--up:#0f9d6a;--dn:#e0334c;--ups:rgba(15,157,106,.12);--dns:rgba(224,51,76,.12);--bl:#2a78d6;--am:#eda100;--nt:#929292}
:root[data-mode="dark"]{--up:#1fc27c;--dn:#f5445c;--ups:rgba(31,194,124,.16);--dns:rgba(245,68,92,.16);--bl:#3987e5;--am:#c98500;--nt:#7a7a7a}
@media(prefers-color-scheme:dark){:root:not([data-mode="light"]){--up:#1fc27c;--dn:#f5445c;--ups:rgba(31,194,124,.16);--dns:rgba(245,68,92,.16);--bl:#3987e5;--am:#c98500;--nt:#7a7a7a}}
.atk .card{background:var(--surface-2);border:0.5px solid var(--border);border-radius:12px;padding:14px 16px;min-width:0}
.atk .lbl{font-size:12px;color:var(--text-muted)}.atk .sub{font-size:12px;color:var(--text-secondary)}
.atk .v{font-size:20px;font-weight:500;letter-spacing:-.01em;line-height:1.15}.atk .v2{font-size:16px;font-weight:500;line-height:1.3;margin-top:3px}
.atk .n{font-variant-numeric:tabular-nums}.atk .up{color:var(--up)}.atk .dn{color:var(--dn)}.atk .mu{color:var(--text-muted)}
.atk .chip{display:inline-flex;align-items:center;gap:6px;font-size:12px;padding:3px 10px;border-radius:999px;border:0.5px solid var(--border);color:var(--text-secondary);white-space:nowrap}
.atk .dot{width:7px;height:7px;border-radius:50%;display:inline-block}.atk .g{display:grid;gap:10px}.atk .row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.atk .p{display:inline-block;font-size:12px;padding:2px 8px;border-radius:6px;white-space:nowrap;background:var(--surface-0);color:var(--text-secondary)}.atk .p.u{background:var(--ups);color:var(--up)}.atk .p.d{background:var(--dns);color:var(--dn)}
.atk td,.atk th{padding:5px 6px;border-top:0.5px solid var(--border);text-align:left;font-weight:400}.atk th{border-top:0;color:var(--text-muted);font-weight:500}
.atk .bar{display:flex;height:10px;border-radius:5px;overflow:hidden;gap:2px}.atk svg text{font-family:inherit}
.atk .ev{display:flex;gap:10px;padding:6px 0;border-top:0.5px solid var(--border);font-size:13px}.atk .ev .dot{margin-top:6px;flex:none}
.atk .kv td:first-child{color:var(--text-secondary);white-space:nowrap}.atk .kv td:last-child{text-align:right}
.atk .opt{display:flex;flex-direction:column;gap:8px}.atk .opt button{margin-top:auto}`;
function css(){if(!document.getElementById('atk-css')){const s=document.createElement('style');s.id='atk-css';s.textContent=CSS;document.head.appendChild(s)}}
const f0=x=>Math.round(x).toLocaleString('en-US'),pc=(x,d=1)=>(x>0?'+':'')+x.toFixed(d)+'%',cl=x=>x>0?'up':x<0?'dn':'mu',dotc=k=>k=='u'?'var(--up)':k=='d'?'var(--dn)':'var(--nt)';
const pill=(v,t)=>`<span class="p ${v>0?'u':v<0?'d':''}">${v>0?'+':''}${v} · ${t}</span>`;
const sv=(h,b,lab)=>`<svg width="100%" viewBox="0 0 300 ${h}" preserveAspectRatio="none" role="img" aria-label="${lab||'sparkline'}" style="display:block;height:${h}px">${b}</svg>`;
function bars(a){const m=Math.max(...a.map(Math.abs))||1,w=300/a.length;return sv(56,`<line x1="0" y1="28" x2="300" y2="28" stroke="var(--border-strong)"/>`+a.map((v,i)=>{const h=Math.abs(v)/m*26;return `<rect x="${i*w+1}" y="${v>=0?28-h:28}" width="${Math.max(1,w-2)}" height="${Math.max(1,h)}" fill="${v>=0?'var(--up)':'var(--dn)'}"/>`}).join(''))}
function line(a,c,ref){const all=ref==null?a:a.concat([ref]),lo=Math.min(...all),hi=Math.max(...all),rg=hi-lo||1,px=i=>2+i/(a.length-1)*296,py=v=>54-(v-lo)/rg*52;
return sv(56,(ref==null?'':`<line x1="0" y1="${py(ref)}" x2="300" y2="${py(ref)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/>`)+`<polyline fill="none" stroke="${c}" stroke-width="2" stroke-linejoin="round" vector-effect="non-scaling-stroke" points="${a.map((v,i)=>px(i)+','+py(v)).join(' ')}"/><circle cx="${px(a.length-1)}" cy="${py(a[a.length-1])}" r="3.5" fill="${c}" stroke="var(--surface-2)" stroke-width="1.5"/>`)}
function candles(K,L,DT,LV,last){const X0=6,X1=596,Y0=14,Y1=236,V0=250,V1=296,n=K.length,st=(X1-X0)/n,bw=Math.max(2,st*.62),ev=[...L.e20,...L.e50,...L.e200].filter(v=>v!=null);
let lo=Math.min(...K.map(k=>k[2]),...LV.map(l=>l[1]),...ev),hi=Math.max(...K.map(k=>k[1]),...LV.map(l=>l[1]),...ev);const pd=(hi-lo)*.05;lo-=pd;hi+=pd;
const Y=p=>Y1-(p-lo)/(hi-lo)*(Y1-Y0),X=i=>X0+st*(i+.5),vm=Math.max(...K.map(k=>k[4]))||1,gs=hi-lo>24000?5000:2000;let s='';
for(let t=Math.ceil(lo/gs)*gs;t<hi;t+=gs)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="var(--border)"/><text x="602" y="${Y(t)+4}" font-size="11" fill="var(--text-muted)">${t/1000}k</text>`;
const pl=(a,c,dash)=>`<polyline fill="none" stroke="${c}" stroke-width="1.6" ${dash?'stroke-dasharray="5 3"':''} stroke-linejoin="round" points="${a.map((v,i)=>v==null?'':X(i).toFixed(1)+','+Y(v).toFixed(1)).filter(Boolean).join(' ')}"/>`;
K.forEach((k,i)=>{const c=k[3]>=k[0]?'var(--up)':'var(--dn)',x=X(i),t=Y(Math.max(k[0],k[3])),b=Y(Math.min(k[0],k[3])),vh=k[4]/vm*(V1-V0);
s+=`<line x1="${x}" y1="${Y(k[1])}" x2="${x}" y2="${Y(k[2])}" stroke="${c}"/><rect x="${x-bw/2}" y="${t}" width="${bw}" height="${Math.max(1,b-t)}" fill="${c}"/><rect x="${x-bw/2}" y="${V1-vh}" width="${bw}" height="${vh}" fill="${c}" opacity=".45"/>`});
s+=pl(L.e200,'var(--text-muted)',1)+pl(L.e50,'var(--am)')+pl(L.e20,'var(--bl)');
LV.forEach(l=>{const c=l[0]=='S'?'var(--up)':'var(--dn)',y=Y(l[1]);s+=`<line x1="${X0}" y1="${y}" x2="${X1}" y2="${y}" stroke="${c}" stroke-dasharray="6 4" opacity=".8"/><text x="10" y="${y-3}" font-size="11" fill="${c}">${l[0]} ${f0(l[1])}</text>`});
const yp=Y(last);s+=`<rect x="598" y="${yp-9}" width="78" height="18" rx="4" fill="var(--text-primary)"/><text x="637" y="${yp+4}" font-size="11" font-weight="500" text-anchor="middle" fill="var(--surface-2)">${f0(last)}</text>`;
for(let i=0;i<n;i+=15)s+=`<text x="${X(i)}" y="306" font-size="11" text-anchor="${i?'middle':'start'}" fill="var(--text-muted)">${DT[i]}</text>`;
return `<svg width="100%" viewBox="0 0 680 306" role="img" aria-label="Daily candlestick chart, last ${n} days, with EMA20, EMA50 and EMA200" style="display:block;overflow:visible">${s}</svg>`}
function fgauge(val){const cx=110,cy=116,r=94,A=(a0,a1,c,o)=>{const p=a=>[cx+r*Math.cos(Math.PI*(1-a)),cy-r*Math.sin(Math.PI*(1-a))],[x0,y0]=p(a0),[x1,y1]=p(a1);return `<path d="M${x0} ${y0} A${r} ${r} 0 0 1 ${x1} ${y1}" fill="none" stroke="${c}" stroke-width="12" opacity="${o}"/>`};
let g=[[0,.25,'var(--dn)',.9],[.25,.45,'var(--dn)',.45],[.45,.55,'var(--nt)',.5],[.55,.75,'var(--up)',.45],[.75,1,'var(--up)',.9]].map(z=>A(z[0]+.004,z[1]-.004,z[2],z[3])).join('');
const an=Math.PI*(1-val/100);g+=`<line x1="${cx}" y1="${cy}" x2="${cx+(r-2)*Math.cos(an)}" y2="${cy-(r-2)*Math.sin(an)}" stroke="var(--text-primary)" stroke-width="2.5" stroke-linecap="round"/><circle cx="${cx}" cy="${cy}" r="5" fill="var(--text-primary)"/><text x="${cx}" y="${cy-30}" text-anchor="middle" font-size="34" font-weight="500" fill="var(--text-primary)">${val}</text><text x="14" y="132" font-size="11" fill="var(--text-muted)">0 · fear</text><text x="206" y="132" text-anchor="end" font-size="11" fill="var(--text-muted)">greed · 100</text>`;
return `<svg width="220" height="132" viewBox="0 0 220 132" role="img" aria-label="Fear and Greed index ${val} of 100">${g}</svg>`}
function ivcurve(IV,EX,HV){const lo=Math.min(...IV,HV)-3,hi=Math.max(...IV,HV)+3,px=i=>24+i/(IV.length-1)*252,py=v=>70-(v-lo)/(hi-lo)*58;
return `<svg width="100%" viewBox="0 0 300 96" role="img" aria-label="ATM implied volatility by expiry against 30-day realised volatility" style="display:block;height:96px"><line x1="14" y1="${py(HV)}" x2="290" y2="${py(HV)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/><text x="290" y="${py(HV)-4}" font-size="11" text-anchor="end" fill="var(--text-muted)">realised ${HV.toFixed(0)}%</text><polyline fill="none" stroke="var(--am)" stroke-width="2" stroke-linejoin="round" points="${IV.map((v,i)=>px(i)+','+py(v)).join(' ')}"/>`+IV.map((v,i)=>`<circle cx="${px(i)}" cy="${py(v)}" r="3.5" fill="var(--am)" stroke="var(--surface-2)" stroke-width="1.5"/><text x="${px(i)}" y="${py(v)-8}" font-size="11" text-anchor="middle" fill="var(--text-secondary)">${v.toFixed(0)}</text><text x="${px(i)}" y="90" font-size="11" text-anchor="middle" fill="var(--text-muted)">${EX[i]}</text>`).join('')+'</svg>'}
function liqmap(q){const B=q.bins,W=320,X0=62,X1=300,T=10,Bt=236,lo=Math.min(...B.map(b=>b[0]))-250,hi=Math.max(...B.map(b=>b[0]))+250,Y=p=>T+(hi-p)/(hi-lo)*(Bt-T),m=Math.max(...B.map(b=>Math.max(b[1],b[2])))||1,BW=X1-X0-104,
th=Math.max(1.5,(Bt-T)*250/(hi-lo)-.6),gs=hi-lo>16000?4000:2000;let s='';
for(let t=Math.ceil(lo/gs)*gs;t<hi;t+=gs)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="var(--border)"/><text x="${X0-6}" y="${Y(t)+4}" font-size="11" text-anchor="end" fill="var(--text-muted)">${t/1000}k</text>`;
B.forEach(b=>{if(b[1])s+=`<rect x="${X0}" y="${Y(b[0])-th/2}" width="${b[1]/m*BW}" height="${th}" fill="var(--dn)" opacity=".85"><title>${f0(b[0])} · longs $${b[1]}M</title></rect>`;if(b[2])s+=`<rect x="${X0}" y="${Y(b[0])-th/2}" width="${b[2]/m*BW}" height="${th}" fill="var(--up)" opacity=".85"><title>${f0(b[0])} · shorts $${b[2]}M</title></rect>`});
const yp=Y(q.price);s+=`<line x1="${X0}" y1="${yp}" x2="${X1}" y2="${yp}" stroke="var(--text-primary)" stroke-dasharray="4 3"/><text x="${X1}" y="${yp-5}" font-size="11" text-anchor="end" fill="var(--text-primary)">price ${f0(q.price)}</text>`;
const lab=(b,v,c)=>{if(!b)return;s+=`<text x="${X0+v/m*BW+6}" y="${Y(b[0])+4}" font-size="11" font-weight="500" fill="${c}" stroke="var(--surface-2)" stroke-width="3" paint-order="stroke">${f0(b[0])} · $${v.toFixed(0)}M</text>`};
lab(q.long_max,q.long_max&&q.long_max[1],'var(--dn)');lab(q.short_max,q.short_max&&q.short_max[2],'var(--up)');
return `<svg width="100%" viewBox="0 0 ${W} 244" role="img" aria-label="Estimated liquidation levels: long liquidations below price, short liquidations above" style="display:block">${s}</svg>`}
const LW={bull:['u','Bullish'],bear:['d','Bearish'],neutral:['','Neutral']};
function optViz(v){const W=232,H=124,L=6,R=154;let s='';const tx=(x,y,t,c,a,w)=>`<text x="${x}" y="${y}" font-size="12" ${w?'font-weight="500"':''} text-anchor="${a||'start'}" fill="${c||'var(--text-muted)'}" stroke="var(--surface-2)" stroke-width="3" paint-order="stroke">${t}</text>`,
sc=a=>{let lo=Math.min(...a),hi=Math.max(...a);const pd=(hi-lo)*.1||1;lo-=pd;hi+=pd;return p=>6+(hi-p)/(hi-lo)*(H-12)},hl=(y,c,d,x0,x1)=>`<line x1="${x0==null?L:x0}" y1="${y}" x2="${x1==null?R:x1}" y2="${y}" stroke="${c}" ${d?'stroke-dasharray="4 3"':''} stroke-width="${d?1.2:1}"/>`;
if(v.t=='grid'){const Y=sc([v.sl,v.tp,v.px]),st=(v.hi-v.lo)/v.n;for(let i=0;i<=v.n;i++){const p=v.lo+st*i;s+=hl(Y(p),p<v.px?'var(--up)':'var(--dn)',0);}
let z=[],x=L+6,up=true,k=0;while(x<R-4){z.push(`${x},${Y(v.px+(up?1:-1)*st*(1+(k%3)))}`);x+=14;up=!up;k++}s+=`<polyline fill="none" stroke="var(--bl)" stroke-width="1.5" opacity=".7" points="${z.join(' ')}"/>`;
s+=hl(Y(v.tp),'var(--up)',1)+hl(Y(v.sl),'var(--dn)',1)+hl(Y(v.px),'var(--text-primary)',1)+tx(R+6,Y(v.tp)+4,'TP '+f0(v.tp),'var(--up)')+tx(R+6,Y(v.px)+4,'now '+f0(v.px),'var(--text-primary)','start',1)+tx(R+6,Y(v.sl)+4,'SL '+f0(v.sl),'var(--dn)')+tx(R+6,(Y(v.hi)+Y(v.px))/2+4,'sell ↑','var(--dn)')+tx(R+6,(Y(v.lo)+Y(v.px))/2+4,'buy ↓','var(--up)')}
else if(v.t=='dca'){const lg=v.dir=='long',Y=sc([...v.fills,v.tp,v.sl]),c=lg?'var(--up)':'var(--dn)',n=v.fills.length,dx=(R-L-28)/Math.max(1,n-1),mx=Math.max(...v.sizes);let pts=[];
v.fills.forEach((f,i)=>{const x=L+10+i*dx,y=Y(f),w=10+14*v.sizes[i]/mx;pts.push(`${x},${y}`);s+=`<rect x="${x-w/2}" y="${y-4}" width="${w}" height="8" rx="2" fill="${c}" opacity="${i?.75:1}"/>`});
s+=`<polyline fill="none" stroke="${c}" stroke-dasharray="2 3" points="${pts.join(' ')}"/>`+hl(Y(v.tp),'var(--up)',1)+hl(Y(v.sl),'var(--dn)',1)+tx(R+6,Y(v.tp)+4,'TP '+f0(v.tp),'var(--up)')+tx(R+6,Y(v.sl)+4,'SL '+f0(v.sl),'var(--dn)')+tx(R+6,Y(v.fills[0])+(Math.abs(Y(v.tp)-Y(v.fills[0]))<14?(Y(v.tp)>Y(v.fills[0])?-6:16):4),'first '+f0(v.fills[0]),'var(--text-primary)','start',1)+tx(R+6,Y(v.fills[n-1])+(lg?-6:14),`${n} orders ${lg?'↓':'↑'}`,c)}
else if(v.t=='swing'){const lg=v.side=='long',Y=sc([v.sl,v.t2,v.px,v.entry]),x0=L+34,x1=R;
s+=`<rect x="${x0}" y="${Math.min(Y(v.entry),Y(v.t2))}" width="${x1-x0}" height="${Math.abs(Y(v.t2)-Y(v.entry))}" fill="var(--ups)"/><rect x="${x0}" y="${Math.min(Y(v.entry),Y(v.t1))}" width="${x1-x0}" height="${Math.abs(Y(v.t1)-Y(v.entry))}" fill="var(--ups)"/><rect x="${x0}" y="${Math.min(Y(v.entry),Y(v.sl))}" width="${x1-x0}" height="${Math.abs(Y(v.sl)-Y(v.entry))}" fill="var(--dns)"/>`;
s+=hl(Y(v.t2),'var(--up)',1,x0)+hl(Y(v.t1),'var(--up)',0,x0)+hl(Y(v.entry),'var(--text-primary)',0,x0)+hl(Y(v.sl),'var(--dn)',0,x0)+`<circle cx="${L+14}" cy="${Y(v.px)}" r="4" fill="var(--bl)"/>`+tx(L+14,Y(v.px)-8,'now','var(--bl)','middle');
s+=tx(R+6,Y(v.t2)+4,'T2 '+f0(v.t2),'var(--up)')+tx(R+6,Y(v.t1)+4,'T1 '+f0(v.t1),'var(--up)')+tx(R+6,Y(v.entry)+4,(lg?'buy ':'sell ')+f0(v.entry),'var(--text-primary)','start',1)+tx(R+6,Y(v.sl)+4,'stop '+f0(v.sl),'var(--dn)')+tx((x0+x1)/2,(Y(v.entry)+Y(v.t1))/2+4,'reward '+v.rr+' : 1','var(--up)','middle',1)}
else{const Y=sc([v.sup,v.res,v.px]),bh=6;s+=`<rect x="${L}" y="${Y(v.res)-bh}" width="${R-L}" height="${bh*2}" rx="3" fill="var(--dns)"/><rect x="${L}" y="${Y(v.sup)-bh}" width="${R-L}" height="${bh*2}" rx="3" fill="var(--ups)"/>`+hl(Y(v.px),'var(--text-primary)',1)+`<circle cx="${(L+R)/2}" cy="${Y(v.px)}" r="4.5" fill="var(--bl)"/>`;
s+=tx(L+6,Y(v.res)+4,'short zone','var(--dn)','start',1)+tx(L+6,Y(v.sup)+4,'long zone','var(--up)','start',1)+tx(R+6,Y(v.res)+4,f0(v.res),'var(--dn)')+tx(R+6,Y(v.sup)+4,f0(v.sup),'var(--up)')+tx(R+6,Y(v.px)+4,'now '+f0(v.px),'var(--text-primary)','start',1)+tx((L+R)/2,Y(v.px)+(v.lean=='short'?-10:18),`waiting · leaning ${v.lean}`,'var(--text-secondary)','middle')}
return `<svg width="100%" viewBox="0 0 ${W} ${H}" role="img" aria-label="Strategy diagram" style="display:block;background:var(--surface-1);border-radius:8px">${s}</svg>`}
const kv=rows=>`<table class="kv" style="width:100%;border-collapse:collapse;font-size:12px">${rows.map(r=>`<tr><td>${r[0]}</td><td class="n">${r[1]}</td></tr>`).join('')}</table>`;
const arw=d=>d=='rising'?'<span class="up">▲ rising</span>':d=='falling'?'<span class="dn">▼ falling</span>':'<span class="mu">▬ flat</span>';
const usd=v=>v>=1e6?'$'+(v/1e6).toFixed(1)+'M':'$'+Math.round(v/1e3)+'K';

function analysis(el,d){css();el.classList.add('atk');const k=d.kpi,dv=d.deriv,T=dv.T,fg=d.fng,q=d.liq,TR={bull:['u','Bullish'],bear:['d','Bearish'],neutral:['','Neutral']};
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${d.sym} analysis at ${d.asof}: price ${f0(k.price)} USDT, Fear and Greed ${fg.now}, trend by timeframe, derivatives trends, option volatility and estimated liquidation levels.</h2>
<div class="row" style="justify-content:space-between;margin-bottom:12px"><div class="row"><span class="chip"><span class="dot" style="background:var(--up)"></span>Live · OKX</span><span class="chip">${d.inst}</span></div><span class="sub n">as of ${d.asof}</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(160px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">Last price</div><div class="v n">${f0(k.price)} <span class="sub">USDT</span></div><div class="sub n ${cl(k.chg24)}">${pc(k.chg24,2)} 24h</div></div>
<div class="card"><div class="lbl">24h range</div><div class="v2 n">${f0(k.lo24)}–${f0(k.hi24)}</div><div class="sub n">daily ATR ${f0(k.atr)} · ${(k.atr/k.price*100).toFixed(1)}% of price</div></div>
<div class="card"><div class="lbl">7d / 30d change</div><div class="v2 n"><span class="${cl(k.chg7)}">${pc(k.chg7)}</span> <span class="mu">/</span> <span class="${cl(k.chg30)}">${pc(k.chg30)}</span></div><div class="sub n">30d realised vol ${k.hv30.toFixed(0)}%</div></div></div>
<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">Daily candles · ${d.K.length} days</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--bl)"></i>EMA20</span><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--am)"></i>EMA50</span><span class="row" style="gap:4px"><i style="width:14px;border-top:2px dashed var(--text-muted)"></i>EMA200</span><span class="row" style="gap:4px"><i style="width:14px;border-top:1px dashed var(--dn)"></i>S / R</span></span></div>${candles(d.K,d.L,d.DT,d.LV,k.price)}</div>
<div class="g" style="grid-template-columns:minmax(0,240px) minmax(0,1fr);margin:10px 0">
<div class="card" style="display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center"><div class="lbl" style="align-self:flex-start">Fear &amp; Greed index</div>${fgauge(fg.now)}<div style="font-size:14px;font-weight:500;margin-top:4px">${fg.label}</div><div class="sub n">yesterday ${fg.prev} · a week ago ${fg.wk}</div></div>
<div class="card"><div class="lbl" style="margin-bottom:4px">Trend by timeframe</div>${d.trend.map(t=>`<div style="display:flex;gap:12px;align-items:center;padding:10px 0;border-top:0.5px solid var(--border)"><span class="n" style="width:28px;font-size:14px;font-weight:500">${t[0]}</span><span class="p ${TR[t[1]][0]}" style="min-width:66px;text-align:center;font-size:13px">${TR[t[1]][1]}</span><span style="font-size:13px;line-height:1.4;color:var(--text-secondary)">${t[2].join(' · ')}</span></div>`).join('')}</div></div>
${d.news?`<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span class="lbl">Macro · top stories from OKX news</span><span class="p ${LW[d.news.lean][0]}" style="font-size:12px">Macro lean · ${LW[d.news.lean][1].toLowerCase()}${d.news.lean!='neutral'?`, ${d.news.count} of ${d.news.total}`:''}</span></div>${d.news.items.map(i=>`<div style="display:flex;gap:12px;align-items:flex-start;padding:10px 0;border-top:0.5px solid var(--border)"><span class="p ${LW[i[0]][0]}" style="flex:none;min-width:64px;text-align:center;font-size:12px">${LW[i[0]][1]}</span><div style="min-width:0"><a href="${i[3]}" target="_blank" rel="noopener" style="font-size:13px;font-weight:500;line-height:1.35;color:var(--text-primary);text-decoration:none">${i[1]}</a><div class="sub" style="margin-top:2px">${i[2]}</div><div style="font-size:13px;line-height:1.4;margin-top:4px;color:var(--text-secondary)">${i[4]}</div></div></div>`).join('')}</div>`:''}
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin:10px 0">
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Funding rate · 30 settlements</span><span style="font-size:13px;font-weight:500">${arw(T.f[0])}</span></div><div style="font-size:13px;line-height:1.4;margin:4px 0 6px">${T.f[1]}.</div>${bars(dv.F)}</div>
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Open interest · 30 days</span><span style="font-size:13px;font-weight:500">${arw(T.oi[0])}</span></div><div style="font-size:13px;line-height:1.4;margin:4px 0 6px">${T.oi[1]}.</div>${line(dv.OI,'var(--bl)')}</div>
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Top traders long / short · 30 days</span><span style="font-size:13px;font-weight:500">${arw(T.ls[0])}</span></div><div style="font-size:13px;line-height:1.4;margin:4px 0 6px">${T.ls[1]}.</div>${line(dv.LS,dv.longp>=50?'var(--up)':'var(--dn)',1)}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr))">
<div class="card"><div class="lbl">Options · ATM implied volatility by expiry</div><div style="font-size:13px;line-height:1.45;margin:4px 0 6px">${d.iv.note}</div>${ivcurve(d.iv.IV,d.iv.EX,d.iv.hv)}${d.iv.opt?`<div class="g" style="grid-template-columns:minmax(0,1fr) minmax(0,1fr);margin-top:10px"><div style="background:var(--surface-1);border-radius:8px;padding:10px 12px"><div class="lbl">Options market says</div><div style="margin:6px 0"><span class="p ${LW[d.iv.opt.lean][0]}" style="font-size:15px;font-weight:500;padding:3px 12px">${LW[d.iv.opt.lean][1]}</span></div><div class="sub" style="line-height:1.4">${d.iv.opt.why}</div></div><div style="background:var(--surface-1);border-radius:8px;padding:10px 12px"><div class="lbl">Expected move by ${d.iv.opt.by}</div><div class="v n" style="margin:6px 0 2px">±${d.iv.opt.move}%</div><div class="sub n">${f0(d.iv.opt.lo)} – ${f0(d.iv.opt.hi)}</div><div class="sub" style="line-height:1.4;margin-top:2px">what options price for the week</div></div></div>`:''}</div>
${q?`<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Liquidation map · estimated</span><span class="row sub" style="gap:10px"><span class="row" style="gap:4px"><i style="width:10px;height:10px;border-radius:2px;background:var(--dn)"></i>longs</span><span class="row" style="gap:4px"><i style="width:10px;height:10px;border-radius:2px;background:var(--up)"></i>shorts</span></span></div>${liqmap(q)}<div class="sub" style="line-height:1.4">Built from ${q.days} days of open-interest build-up across 10–100x leverage.${q.recent&&q.recent.hours?` Last ${q.recent.hours==1?'hour':q.recent.hours+' hours'}: ${usd(q.recent.long)} of longs and ${usd(q.recent.short)} of shorts liquidated.`:''}</div></div>`:''}</div>`}

function conclusion(el,d){css();el.classList.add('atk');const S=d.score,ob=d.ob;
const side=(nm,v,arr,c,cls)=>`<div class="card"><div class="row" style="justify-content:space-between;align-items:baseline"><span style="font-size:14px;font-weight:500">${nm} case</span><span class="n" style="font-size:28px;font-weight:500;color:${c}">${v}<span class="sub"> /100</span></span></div>${arr.length?arr.map(r=>`<div class="ev"><span class="p ${cls} n" style="flex:none;min-width:30px;text-align:center">+${r[0]}</span><span><span style="color:var(--text-secondary)">${r[1]} · </span>${r[2]}</span></div>`).join(''):`<div class="ev"><span class="mu">No signal on this side today</span></div>`}</div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Conclusion: ${d.head}. Long score ${S.long}, short score ${S.short}; options: ${d.opts.map(o=>o.kind).join(', ')}.</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Market direction · long vs short</div><div style="font-size:18px;font-weight:500;line-height:1.25;margin:4px 0 2px">${d.head}</div><div class="sub" style="margin-bottom:10px">${d.bias} · as of ${d.asof}</div>
<div class="row n" style="justify-content:space-between;font-size:13px;font-weight:500;margin-bottom:4px"><span class="up">Long ${S.long}</span><span class="dn">Short ${S.short}</span></div><div style="position:relative"><div class="bar" style="height:12px"><div style="width:${S.long}%;background:var(--up)"></div><div style="flex:1;background:var(--dn)"></div></div><i style="position:absolute;left:50%;top:-3px;bottom:-3px;border-left:1.5px solid var(--text-primary)"></i></div><div class="sub" style="margin-top:6px">A directional trade needs one side at 55 or more and a 15-point lead.</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr));margin-bottom:10px">${side('Long',S.long,S.L,'var(--up)','u')}${side('Short',S.short,S.S,'var(--dn)','d')}</div>
<div class="card" style="margin-bottom:10px"><div class="lbl" style="margin-bottom:2px">Entry conditions · all three required for a directional trade</div><div class="g" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))">${d.CK.map(c=>`<div style="display:flex;gap:10px;align-items:flex-start;padding:8px 0;border-top:0.5px solid var(--border)"><span style="flex:none;width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:${c[1]?'var(--ups)':'var(--dns)'};color:${c[1]?'var(--up)':'var(--dn)'};font-size:14px;font-weight:500">${c[1]?'✓':'✕'}</span><span><div style="font-size:13px;font-weight:500">${c[0]}</div><div class="sub n">${c[2]}</div></span></div>`).join('')}</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(240px,1fr));margin-top:6px"><div><div class="lbl" style="margin:6px 0">Patterns &amp; divergences</div><div style="line-height:2">${d.PT.map(p=>`<span class="p ${p[1]=='u'?'u':p[1]=='d'?'d':''}">${p[0]}</span> `).join('')||'<span class="mu">none detected</span>'}</div></div>
<div><div class="lbl" style="margin:6px 0 4px">Order book · top 50 levels</div><div class="bar"><div style="width:${ob.bidp}%;background:var(--up)"></div><div style="flex:1;background:var(--dn)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:4px"><span>bids ${f0(ob.bid)} ${d.base}</span><span>imbalance ${(ob.imb>0?'+':'')+ob.imb}%</span><span>asks ${f0(ob.ask)} ${d.base}</span></div></div></div></div>
<div class="lbl" style="margin:10px 0 6px 2px">Opening options · pick one, each button opens a preview (nothing is placed without confirmation)</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">${d.opts.map(o=>`<div class="card opt" style="${o.star?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span style="font-size:14px;font-weight:500"><span class="p" style="margin-right:6px">${o.tag}</span>${o.kind}</span>${o.star?'<span class="p u">best fit now</span>':''}</div><div class="sub">${o.fit}</div><div style="font-size:13px;line-height:1.45">${o.why}</div>${o.viz?optViz(o.viz):''}${kv(o.rows)}${o.cmd.startsWith('okx')?`<button data-cmd="${o.tag}">Confirm option ${o.tag} ↗</button>`:''}</div>`).join('')}</div>
<div class="sub" style="margin-top:10px">${d.foot}</div>`;
el.querySelectorAll('button[data-cmd]').forEach(b=>{const o=d.opts.find(x=>x.tag==b.dataset.cmd);b.onclick=()=>window.sendPrompt&&sendPrompt(`Place option ${o.tag}.`)})}
/* ---- Dual Investment (DCD) buy-low advisory views ---- */
const pct=(x,d=1)=>(x*100).toFixed(d)+'%',spc=(x,d=1)=>(x>=0?'+':'')+(x*100).toFixed(d)+'%';
function ladder(L){const X0=78,X1=540,T=14,B=318,lo0=Math.min(L.floor,...L.strikes.map(s=>s[0]),...L.walls.map(w=>w[0])),pad=(L.spot-lo0)*.1,lo=lo0-pad,hi=L.spot+pad,Y=p=>T+(hi-p)/(hi-lo)*(B-T),mw=Math.max(1,...L.walls.map(w=>w[1]));let s='';
const st=(hi-lo)>14000?2000:1000;for(let p=Math.ceil(lo/st)*st;p<hi;p+=st)s+=`<line x1="${X0}" y1="${Y(p)}" x2="${X1}" y2="${Y(p)}" stroke="var(--border)"/><text x="${X0-8}" y="${Y(p)+4}" font-size="12" text-anchor="end" fill="var(--text-muted)">${f0(p)}</text>`;
s+=`<rect x="${X0}" y="${Y(L.spot)}" width="${X1-X0}" height="${Y(L.floor)-Y(L.spot)}" fill="var(--bl)" opacity=".07"/><rect x="${X0}" y="${Y(L.floor)}" width="${X1-X0}" height="${B-Y(L.floor)}" fill="var(--up)" opacity=".10"/>`;
s+=`<text x="${X0+10}" y="${Y(L.spot)+20}" font-size="12.5" fill="var(--bl)">Expected range to ${L.date}</text><text x="${X1-10}" y="${B-10}" font-size="12.5" font-weight="500" text-anchor="end" fill="var(--up)">Strikes down here: 9 in 10 you keep your USDT</text>`;
L.walls.forEach(w=>{const bw=Math.max(6,w[1]/mw*110),y=Y(w[0]);s+=`<rect x="${X1-bw}" y="${y-6}" width="${bw}" height="12" rx="3" fill="var(--am)"><title>${f0(w[0])} · ${f0(w[1])} BTC of put protection</title></rect><text x="${X1-bw-6}" y="${y+4}" font-size="11.5" text-anchor="end" fill="var(--text-secondary)">${f0(w[1])} BTC</text>`});
s+=`<line x1="${X0}" y1="${Y(L.spot)}" x2="${X1}" y2="${Y(L.spot)}" stroke="var(--text-primary)" stroke-width="1.5" stroke-dasharray="5 4"/><text x="${X1+8}" y="${Y(L.spot)+4}" font-size="12.5" font-weight="500" fill="var(--text-primary)">BTC now ${f0(L.spot)}</text>`;
s+=`<line x1="${X0}" y1="${Y(L.floor)}" x2="${X1}" y2="${Y(L.floor)}" stroke="var(--up)" stroke-width="2.5"/><text x="${X1+8}" y="${Y(L.floor)+4}" font-size="12.5" font-weight="500" fill="var(--up)">Safe line ${f0(L.floor)}</text>`;
L.strikes.forEach(k=>{const y=Y(k[0]);s+=`<circle cx="${X0+22}" cy="${y}" r="${k[2]?6:4.5}" fill="var(--up)" stroke="var(--surface-2)" stroke-width="1.5"/><text x="${X0+34}" y="${y+4}" font-size="12" font-weight="${k[2]?500:400}" fill="var(--text-primary)">${k[1]} · ${f0(k[0])}</text>`});
return `<svg width="100%" viewBox="0 0 680 330" role="img" aria-label="Price ladder: BTC now ${f0(L.spot)}, safe line ${f0(L.floor)}, recommended strikes and option traders' put protection" style="display:block;overflow:visible">${s}</svg>`}
function richBar(r){const m=Math.max(r.iv7,r.hv30)*1.1;return `<div style="display:flex;flex-direction:column;gap:10px;margin:10px 0">`+[['Swings the options are priced for',r.iv7,'var(--bl)'],['Swings BTC actually had · last 30 days',r.hv30,'var(--nt)']].map(x=>`<div><div class="row" style="justify-content:space-between"><span style="font-size:13px;color:var(--text-secondary)">${x[0]}</span><span class="n" style="font-size:14px;font-weight:500">${pct(x[1],0)} a year</span></div><div style="height:12px;border-radius:6px;background:var(--surface-0);margin-top:4px"><div style="height:12px;border-radius:6px;width:${(x[1]/m*100).toFixed(1)}%;background:${x[2]}"></div></div></div>`).join('')+`</div>`}
function macroCard(m){if(!m)return '';const E=m.events||[],span=Math.max(1,m.end-m.now),x=t=>Math.min(97,Math.max(3,(t-m.now)/span*100)),wc=w=>w=='Very high'?'var(--dn)':w=='High'?'var(--am)':'var(--bl)',ws=w=>w=='Very high'?26:w=='High'?22:18;
const D=(t,o)=>new Date(t+8*3600e3).toLocaleString('en-US',Object.assign({timeZone:'UTC'},o)),day=t=>D(t,{weekday:'short',month:'short',day:'numeric'}).replace(',',''),dl=t=>D(t,{weekday:'short'})+' '+D(t,{day:'numeric'}),hm=t=>D(t,{hour:'2-digit',minute:'2-digit',hour12:false});
const days=[];for(let t=Math.ceil((m.now+8*3600e3)/864e5)*864e5-8*3600e3;t<m.end;t+=864e5)days.push(t);
const C=m.cushions,W=680,X0=44,X1=640,Y0=34,Y1=108,YA=178,X=t=>X0+(t-m.now)/span*(X1-X0);
const hi=Math.max(...C.map(c=>c.base)),lo=Math.min(...C.map(c=>c.floor)),Y=v=>Y0+(hi-v)/Math.max(1,hi-lo)*(Y1-Y0);
const P=k=>C.map(c=>X(c.ts).toFixed(1)+','+Y(c[k]).toFixed(1)),poly=P('base').concat(P('floor').reverse()).join(' ');
const tx=(x,y,t,o)=>`<text x="${x}" y="${y}" font-size="12" text-anchor="${(o&&o.a)||'middle'}" fill="${(o&&o.c)||'var(--text-secondary)'}"${o&&o.w?' font-weight="500"':''}>${t}</text>`;
const seen={};
const ev=E.map((e,i)=>{const n=seen[e.ts]=(seen[e.ts]||0)+1,cx=X(e.ts),cy=YA-(n-1)*24,r=e.weight=='Very high'?12:e.weight=='High'?11:10,after=e.ts>=m.settleTs;
return `<g><title>${e.name} · ${e.when}</title><circle cx="${cx}" cy="${cy}" r="${r}" fill="${after?'var(--surface-2)':wc(e.weight)}" stroke="${wc(e.weight)}" stroke-width="2"/>${tx(cx,cy+4,i+1,{c:after?wc(e.weight):'#fff',w:1})}</g>`}).join('');
const grid=days.map(t=>`<line x1="${X(t)}" x2="${X(t)}" y1="${Y0-6}" y2="${YA+30}" stroke="var(--border)" stroke-width="0.5"/>${tx(X(t),YA+46,dl(t),{c:'var(--text-muted)'})}`).join('');
const pts=C.map(c=>{const sel=c.ts==m.settleTs;return `<circle cx="${X(c.ts)}" cy="${Y(c.floor)}" r="${sel?6:4}" fill="var(--up)"${sel?' stroke="var(--text-primary)" stroke-width="1.5"':''}/>${tx(X(c.ts),Y(c.floor)+(sel?22:18),f0(c.floor),{c:sel?'var(--up)':'var(--text-secondary)',w:sel})}${c.usdt>=1?tx(X(c.ts),Y(c.floor)+(sel?36:32),'−'+f0(c.usdt),{c:'var(--am)'}):''}`}).join('');
const tl=`<svg viewBox="0 0 ${W} ${YA+56}" width="100%" role="img" aria-label="Safe line by settlement date, lowered for macro events" style="display:block;margin-top:6px">${grid}<polygon points="${poly}" fill="var(--am)" opacity=".22"/><polyline points="${P('base').join(' ')}" fill="none" stroke="var(--nt)" stroke-width="1.5" stroke-dasharray="4 4"/><polyline points="${P('floor').join(' ')}" fill="none" stroke="var(--up)" stroke-width="2"/>${pts}${tx(X0-6,Y0-14,'Safe line at each 16:00 settlement · dashed = before event cushion',{a:'start',c:'var(--text-muted)'})}<line x1="${X0}" x2="${X1+20}" y1="${YA}" y2="${YA}" stroke="var(--border-strong)"/>${ev}</svg>`;
const rows=E.map((e,i)=>{const after=e.ts>=m.settleTs;return `<div class="ev" style="font-size:13.5px;align-items:baseline;gap:8px"><span class="n" style="min-width:18px;font-weight:500;color:${wc(e.weight)}">${i+1}</span><span style="flex:1"><span style="font-weight:500">${e.name}</span> <span class="mu">· ${day(e.ts)}, ${hm(e.ts)} UTC+8${e.fc?` · forecast ${e.fc}`:''}${after?' · after this settlement':''}</span></span><span class="p n" style="color:${wc(e.weight)}">${e.weight} · ±${e.budget.toFixed(2).replace(/0$/,'')}% cushion</span></div>`}).join('');
const head=E.length?`${E.length} major US release${E.length!=1?'s':''} this week${m.minor?` · ${m.minor} smaller release${m.minor!=1?'s':''} also counted in the cushion`:''}`:'No major US releases this week';
const empty=E.length?'':`<div style="font-size:13.5px;color:var(--text-secondary)">Nothing on the US calendar is likely to move BTC before settlement, so the safe line carries no extra cushion.</div>`;
return `<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span style="font-size:15px;font-weight:500">Macro events this week</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:10px;height:10px;border-radius:50%;background:var(--dn)"></i>very high</span><span class="row" style="gap:4px"><i style="width:10px;height:10px;border-radius:50%;background:var(--am)"></i>high</span><span class="row" style="gap:4px"><i style="width:10px;height:10px;border-radius:50%;background:var(--bl)"></i>low</span><span class="row" style="gap:4px"><i style="width:10px;height:10px;border-radius:50%;border:2px solid var(--nt);box-sizing:border-box"></i>hollow = after our settlement</span></span></div><div class="sub" style="margin-bottom:2px">${head}${m.fallback?' · no importance-3 release this week':''}</div>${tl}<div style="margin-top:6px">${rows}</div>${empty}</div>`}
function dcdAnalysis(el,d){css();el.classList.add('atk');const L=d.ladder,r=d.rich;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">What the options market says for BTC buy-low Dual Investment at ${d.asof}: BTC ${f0(d.spot)}, typical move this week ±${pct(d.move7,1)}, safe line ${f0(L.floor)} by ${L.date}.</h2>
<div class="row" style="justify-content:space-between;margin-bottom:12px"><div class="row"><span class="chip"><span class="dot" style="background:var(--up)"></span>Live · OKX</span><span class="chip">BTC-USDT Dual Investment · buy low · USDT deposit</span></div><span class="sub n">as of ${d.asof}</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(160px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">BTC now</div><div class="v n">${f0(d.spot)}</div><div class="sub n ${cl(d.chg24)}">${spc(d.chg24,2)} in 24h</div></div>
<div class="card"><div class="lbl">Typical move this week</div><div class="v n">±${pct(d.move7,1)}</div><div class="sub n">about ±${f0(d.spot*d.move7)} USDT</div></div>
<div class="card"><div class="lbl">Safe line by ${L.date}</div><div class="v n up">${f0(L.floor)}</div><div class="sub n">${pct(1-L.floor/d.spot,1)} below today · 9 in 10 odds</div></div></div>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:15px;font-weight:500">What the options market is telling you</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:14px;height:8px;border-radius:2px;background:var(--am)"></i>protection option traders bought</span><span class="row" style="gap:4px"><i style="width:9px;height:9px;border-radius:50%;background:var(--up)"></i>our strikes</span></span></div>${ladder(L)}
<div style="margin-top:6px">${d.notes.map(n=>`<div class="ev" style="font-size:13.5px"><span class="dot" style="background:var(--bl)"></span><span>${n}</span></div>`).join('')}</div></div>
${macroCard(d.macro)}`}
function dcdConclusion(el,d){css();el.classList.add('atk');const N=d.notional;
const card=t=>{const p=t.pick;
if(t.same)return `<div class="card opt"><span class="p" style="align-self:flex-start">${t.name}</span><div style="font-size:15px;font-weight:500">Same as Balanced this week</div><div style="font-size:13px;line-height:1.45;color:var(--text-secondary)">${t.why}</div></div>`;
if(!p)return `<div class="card opt"><span class="p" style="align-self:flex-start">${t.name}</span><div style="font-size:15px;font-weight:500">Nothing fits this profile this week</div><div style="font-size:13px;color:var(--text-secondary)">Keep the USDT in flexible savings and re-check tomorrow.</div></div>`;
const usdt=(N*(1+p.absYield)).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}),btc=(N/p.strike*(1+p.absYield)).toFixed(4);
return `<div class="card opt" style="${t.house?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span class="p ${t.house?'u':''}" style="font-weight:500">${t.name}${t.house?' · our pick':''}</span>${p.fallback?'<span class="p d">closest available</span>':''}</div>
<div class="row" style="align-items:baseline;gap:8px"><span class="v n" style="font-size:28px">${pct(p.apy,1)}</span><span class="sub">a year · ${p.days.toFixed(1)} days</span></div>
<div class="n" style="font-size:13px">${[['Strike',`${f0(p.strike)} <span class="mu">−${pct(p.distance,1)}</span>`],['Settles',`${p.expDate}, 16:00 UTC+8`],['Chance you get BTC',`<span class="${p.pEx<=.1?'up':p.pEx<=.2?'':'dn'}" style="font-weight:500">${pct(p.pEx,0)}</span>`]].map(r=>`<div style="display:flex;justify-content:space-between;gap:8px;padding:5px 0;border-top:0.5px solid var(--border)"><span style="color:var(--text-secondary)">${r[0]}</span><span style="text-align:right">${r[1]}</span></div>`).join('')}</div>
<div class="n" style="font-size:13px;line-height:1.6;background:var(--surface-0);border-radius:8px;padding:8px 10px"><div>BTC stays above ${f0(p.strike)} → <span style="font-weight:500">${usdt} USDT</span></div><div>BTC ends below → <span style="font-weight:500">${btc} BTC</span></div></div>
<div style="font-size:13px;line-height:1.45;color:var(--text-secondary)"><span style="color:var(--text-primary);font-weight:500">Why · </span>${p.why}</div>
<button data-tier="${t.key}">Subscribe ${f0(N)} USDT · ${t.name} ↗</button></div>`};
const S=d.shelf,tierBg={conservative:'var(--ups)',balanced:'rgba(42,120,214,.16)',aggressive:'rgba(237,161,0,.2)',avoid:'var(--surface-0)'};
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Recommendation: ${d.head}. ${d.tiers.filter(t=>t.pick&&!t.same).map(t=>`${t.name}: ${t.pick.productId} at ${pct(t.pick.apy,1)} a year, ${pct(t.pick.pEx,0)} chance of ending up with BTC`).join('; ')}.</h2>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between"><span class="lbl">Our read</span><span class="sub n">as of ${d.asof}</span></div><div style="font-size:18px;font-weight:500;line-height:1.3;margin:4px 0 6px">${d.head}</div>${d.points.map(e=>`<div class="ev" style="font-size:13.5px"><span class="dot" style="background:${dotc(e[2])}"></span><span><span style="font-weight:500">${e[0]} · </span>${e[1]}</span></div>`).join('')}</div>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:15px;font-weight:500">Every product this week · yield and chance you end up with BTC</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:var(--ups)"></i>conservative ≤ 5 %</span><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:rgba(42,120,214,.16)"></i>balanced ≤ 10 %</span><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:rgba(237,161,0,.2)"></i>aggressive ≤ 20 %</span><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:var(--surface-0);border:0.5px solid var(--border)"></i>not recommended</span></span></div>
<div style="overflow-x:auto"><table style="width:100%;border-collapse:separate;border-spacing:3px;font-size:11px"><tr><th style="text-align:right;border:0">strike ↓ · settles →</th>${S.exps.map(x=>`<th style="text-align:center;border:0">${x[1]}<br><span class="n mu" style="font-weight:400">safe line ${f0(x[2])}</span></th>`).join('')}</tr>${S.strikes.map(k=>`<tr><td class="n" style="text-align:right;border:0;font-weight:500;white-space:nowrap">${f0(k)} <span class="mu" style="font-weight:400">−${((1-k/d.spot)*100).toFixed(1)}%</span></td>${S.exps.map(x=>{const c=S.cells[x[0]+'|'+Math.round(k)];if(!c)return '<td style="border:0;text-align:center;color:var(--text-muted)">·</td>';return `<td style="border:0;text-align:center;border-radius:5px;padding:4px 2px;background:${tierBg[c[2]]};${c[3]?'outline:1.5px solid var(--text-primary);':''}${c[2]=='avoid'?'color:var(--text-muted)':''}"><span class="n" style="font-weight:500;font-size:12px">${pct(c[0],1)}</span><br><span class="n" style="font-size:10.5px">${pct(c[1],0)}${c[3]?' · '+c[3]:''}</span></td>`}).join('')}</tr>`).join('')}</table></div><div class="sub" style="margin-top:6px">Each cell: yield a year / chance you end up with BTC. Outlined cells are our picks.</div></div>
<div class="lbl" style="margin:0 0 6px 2px">Our picks by risk profile · ${f0(N)} USDT · nothing is placed until you confirm</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin-bottom:10px">${d.tiers.map(card).join('')}</div>
<div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-tier]').forEach(b=>{const t=d.tiers.find(x=>x.key==b.dataset.tier);b.onclick=()=>window.sendPrompt&&sendPrompt(`Put ${f0(N)} USDT into the ${t.name.toLowerCase()} pick from your report (${t.pick.productId}).`)})}
/* ---------- sentiment radar (scenario 3) ---------- */
const RCSS=`.atk .rc{display:flex;flex-direction:column;gap:9px}.atk .rc h4{margin:0;font-size:11px;font-weight:500;letter-spacing:.04em;text-transform:uppercase;color:var(--text-muted)}
.atk .fl{display:flex;gap:8px;font-size:12.5px;line-height:1.4;color:var(--text-secondary)}.atk .fl .dot{margin-top:5px;flex:none}
.atk .lk{display:block;font-size:12.5px;line-height:1.35;color:var(--bl);text-decoration:none;padding:3px 0}.atk .lk:hover{text-decoration:underline}.atk .lk span{color:var(--text-muted)}
.atk .vd{font-size:12px;font-weight:500;padding:3px 10px;border-radius:999px;white-space:nowrap}.atk .vd.vw{background:var(--ups);color:var(--up)}.atk .vd.vr{background:var(--dns);color:var(--dn)}.atk .vd.vn{background:var(--surface-0);color:var(--text-secondary)}
.atk .big{font-size:18px;font-weight:500;line-height:1.25;margin:4px 0 2px}.atk .rt td,.atk .rt th{font-size:12.5px;padding:6px 6px}.atk .rt td.n,.atk .rt th.n{text-align:right}`;
function rcss(){css();if(!document.getElementById('atk-rcss')){const s=document.createElement('style');s.id='atk-rcss';s.textContent=RCSS;document.head.appendChild(s)}}
const fdot=k=>k=='r'?'var(--dn)':k=='a'?'var(--am)':'var(--up)',sg=(x,d=1)=>(x>0?'+':x<0?'−':'')+Math.abs(x).toFixed(d)+'%',esc=t=>String(t).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const vpill=(k,t)=>`<span class="vd ${k==1?'vw':k==2?'vr':'vn'}">${t||(k==1?'Worth watching':k==2?'Too risky to chase':'Context')}</span>`;
function radarMap(P,thrX,thrY){const X0=52,X1=664,Y0=26,Y1=318,lx=v=>Math.log2(Math.min(8,Math.max(.4,v))),xa=lx(.4),xb=lx(8);
const ys=P.map(p=>p[2]),lo=Math.max(-40,Math.min(-15,...ys)-4),hi=Math.min(60,Math.max(25,...ys)+6),X=v=>X0+(lx(v)-xa)/(xb-xa)*(X1-X0),Y=v=>Y1-(Math.min(hi,Math.max(lo,v))-lo)/(hi-lo)*(Y1-Y0),vm=Math.max(...P.map(p=>p[3]))||1;
let s=`<rect x="${X(thrX)}" y="${Y0}" width="${X1-X(thrX)}" height="${Y(thrY)-Y0}" fill="var(--ups)" opacity=".55"/><text x="${X1-6}" y="${Y0+15}" text-anchor="end" font-size="12" font-weight="500" fill="var(--text-secondary)">attention and leverage arriving together</text>`;
[.5,1,2,4,8].forEach(t=>{s+=`<line x1="${X(t)}" y1="${Y0}" x2="${X(t)}" y2="${Y1}" stroke="var(--border)"/><text x="${X(t)}" y="${Y1+16}" font-size="12" text-anchor="middle" fill="var(--text-muted)">${t}×</text>`});
for(let t=Math.ceil(lo/10)*10;t<=hi;t+=10)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="${t==0?'var(--border-strong)':'var(--border)'}"/><text x="${X0-6}" y="${Y(t)+4}" font-size="12" text-anchor="end" fill="var(--text-muted)">${t>0?'+':''}${t}%</text>`;
s+=`<line x1="${X(thrX)}" y1="${Y0}" x2="${X(thrX)}" y2="${Y1}" stroke="var(--text-muted)" stroke-dasharray="4 3"/><line x1="${X0}" y1="${Y(thrY)}" x2="${X1}" y2="${Y(thrY)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/>`;
const used=[];P.slice().sort((a,b)=>a[4]-b[4]||b[3]-a[3]).forEach(p=>{const x=X(p[1]),y=Y(p[2]),r=4+Math.sqrt(p[3]/vm)*15,c=p[4]==1?'var(--up)':p[4]==2?'var(--dn)':p[4]==3?'var(--am)':'var(--nt)';
s+=`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r.toFixed(1)}" fill="${c}" fill-opacity="${p[4]?.3:.16}" stroke="${c}" stroke-width="${p[4]?1.5:.75}" stroke-opacity="${p[4]?1:.5}"><title>${p[0]} · attention ${p[1].toFixed(1)}× its weekly norm (${f0(p[8])} mentions) · open interest ${sg(p[2])} in 24h, ${sg(p[6])} in 4h, ${sg(p[5])} in 1h · price ${sg(p[7])}</title></circle>`;
if(p[4]){let ly=y+4,left=x>X1-70;for(let k=0;k<6&&used.some(u=>Math.abs(u[0]-x)<64&&Math.abs(u[1]-ly)<14);k++)ly+=14;used.push([x,ly]);s+=`<text x="${left?x-r-5:x+r+5}" y="${ly}" font-size="13" font-weight="500" text-anchor="${left?'end':'start'}" fill="var(--text-primary)" stroke="var(--surface-2)" stroke-width="3" paint-order="stroke">${p[0]}</text>`}
else if(Math.abs(p[2])>=12||p[1]>=2.2)s+=`<text x="${x+r+4}" y="${y+4}" font-size="11" fill="var(--text-muted)">${p[0]}</text>`});
s+=`<text x="${(X0+X1)/2}" y="${Y1+34}" font-size="12" text-anchor="middle" fill="var(--text-secondary)">Attention · mentions in the last 24h vs the coin's own weekly norm →</text><text transform="translate(13 ${(Y0+Y1)/2}) rotate(-90)" font-size="12" text-anchor="middle" fill="var(--text-secondary)">Open interest · 24h change →</text>`;
return `<svg width="100%" viewBox="0 0 680 356" role="img" aria-label="Attention versus open-interest change for every alt perpetual scanned" style="display:block">${s}</svg>`}
function radarScan(el,d){rcss();el.classList.add('atk');
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Sentiment radar · alt perpetuals on OKX · as of ${d.asof}</div><div class="big">${d.head}</div><div class="sub">${d.sub}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(140px,1fr));margin-bottom:10px">${d.kpi.map(k=>`<div class="card"><div class="lbl">${k[0]}</div><div class="v n" style="font-size:26px;margin-top:2px">${k[1]}</div><div class="sub">${k[2]}</div></div>`).join('')}</div>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span style="font-size:14px;font-weight:500">Where attention and leverage are moving</span><span class="row sub"><span class="row" style="gap:4px"><span class="dot" style="background:var(--up)"></span>worth watching</span><span class="row" style="gap:4px"><span class="dot" style="background:var(--dn)"></span>too risky to chase</span><span class="row" style="gap:4px"><span class="dot" style="background:var(--nt)"></span>rest of the market</span><span>bubble = 24h volume</span></span></div>${radarMap(d.pts,d.thrX,d.thrY)}</div>
${d.themes.length?`<div class="row" style="margin-bottom:10px"><span class="lbl">Narratives in play</span>${d.themes.map(t=>`<span class="chip"><b style="font-weight:500;color:var(--text-primary)">${t[0]}</b>${t[1].join(' · ')}</span>`).join('')}</div>`:''}
<div class="card"><div style="overflow-x:auto"><table class="rt" style="width:100%;border-collapse:collapse"><tr><th>Coin</th><th>Narrative</th><th class="n">Attention</th><th class="n">Mentions 24h</th><th class="n">OI 24h</th><th class="n">OI 4h</th><th class="n">Price 24h</th><th class="n">Volume vs norm</th><th class="n">Read</th></tr>${d.rows.map(r=>`<tr><td style="font-weight:500">${r[0]}</td><td class="mu">${r[1]}</td><td class="n" style="font-weight:500">${r[2].toFixed(1)}×</td><td class="n">${f0(r[3])}</td><td class="n ${cl(r[4])}">${sg(r[4])}</td><td class="n ${cl(r[5])}">${sg(r[5])}</td><td class="n ${cl(r[6])}">${sg(r[6])}</td><td class="n">${r[7].toFixed(1)}×</td><td class="n">${vpill(r[8])}</td></tr>`).join('')}</table></div><div class="sub" style="margin-top:6px">${d.note}</div></div>`}
function duo(a,b){const W=300,H=74,f=(arr,y0,y1)=>{const lo=Math.min(...arr),hi=Math.max(...arr),rg=hi-lo||1;return arr.map((v,i)=>(2+i/(arr.length-1)*(W-4)).toFixed(1)+','+(y1-(v-lo)/rg*(y1-y0)).toFixed(1)).join(' ')};
return `<svg width="100%" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="48-hour price with open interest underneath" style="display:block;height:${H}px">${a.length>1?`<polyline fill="none" stroke="var(--text-primary)" stroke-width="1.8" vector-effect="non-scaling-stroke" stroke-linejoin="round" points="${f(a,4,40)}"/>`:''}${b.length>1?`<polyline fill="none" stroke="var(--bl)" stroke-width="1.8" vector-effect="non-scaling-stroke" stroke-linejoin="round" points="${f(b,48,72)}"/>`:''}</svg>`}
function radarCandidates(el,d){rcss();el.classList.add('atk');
const fl=a=>a.map(x=>`<div class="fl"><span class="dot" style="background:${fdot(x[0])}"></span><span>${x[1]}</span></div>`).join('');
const card=c=>`<div class="card rc" style="${c.k==1?'border:1.5px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span class="row" style="gap:8px"><span style="font-size:20px;font-weight:500">${c.ccy}</span><span class="chip">${c.theme}</span></span>${vpill(c.k)}</div>
<div class="row" style="align-items:baseline;gap:10px"><span class="v n">${c.lastS}</span><span class="n ${cl(c.chg24)}" style="font-size:14px;font-weight:500">${sg(c.chg24)}</span><span class="sub">24h</span></div>
<div style="font-size:13.5px;line-height:1.45;font-weight:500">${c.why}</div>
<div><h4>What is driving it</h4><div style="font-size:13px;line-height:1.45;margin-top:3px">${c.driver}</div></div>
<div><h4>Do price and volume support it</h4><div class="g" style="grid-template-columns:repeat(4,1fr);gap:6px;margin:5px 0">${c.stats.map(s=>`<div><div class="lbl" style="font-size:11px">${s[0]}</div><div class="n ${s[2]||''}" style="font-size:15px;font-weight:500">${s[1]}</div></div>`).join('')}</div>${duo(c.px,c.oi)}<div class="row sub" style="gap:12px;font-size:11px"><span class="row" style="gap:4px"><i style="width:12px;height:2px;background:var(--text-primary)"></i>price · 48h</span><span class="row" style="gap:4px"><i style="width:12px;height:2px;background:var(--bl)"></i>open interest</span></div><div class="fl" style="margin-top:4px"><span class="dot" style="background:${dotc(c.confK)}"></span><span>${c.conf}</span></div></div>
<div><h4>Crowded positioning</h4>${fl(c.crowd)}</div><div><h4>Liquidity</h4>${fl(c.liq)}</div>
<div><h4>Read more</h4>${c.links.map(l=>`<a class="lk" href="${esc(l[1])}" target="_blank" rel="noopener">${esc(l[0])} <span>· ${esc(l[2])} ↗</span></a>`).join('')}</div>
${c.k==1?`<button data-ccy="${c.ccy}" style="margin-top:auto">Design a position plan for ${c.ccy} ↗</button>`:''}</div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Our read · candidates · as of ${d.asof}</div><div class="big">${d.head}</div><div class="sub">${d.bias}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));margin-bottom:10px">${d.cards.map(card).join('')}</div><div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-ccy]').forEach(b=>b.onclick=()=>window.sendPrompt&&sendPrompt(`Design a position plan for ${b.dataset.ccy}.`))}
function radarPlan(el,d){rcss();el.classList.add('atk');const m=50+d.score/2;
const tier=t=>`<div class="card opt" style="${t.house?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span class="p ${t.house?'u':''}" style="font-weight:500">${t.name}${t.house?' · house pick':''}</span><span class="sub">${t.fit}</span></div>
<div class="row" style="align-items:baseline;gap:8px"><span class="v n" style="font-size:18px">${t.entry}</span><span class="sub">${t.entryNote}</span></div>
${kv([['Stop',`<span class="dn" style="font-weight:500">${t.stop}</span> <span class="mu">${t.stopPct}</span>`],['Take profit 1 · half',`<span class="up" style="font-weight:500">${t.tp1}</span> <span class="mu">${t.tp1Pct}</span>`],['Take profit 2 · half',`<span class="up" style="font-weight:500">${t.tp2}</span> <span class="mu">${t.tp2Pct}</span>`],['Position',`${t.notional} USDT <span class="mu">${t.contracts}</span>`],['Margin · leverage',`${t.margin} USDT · ${t.lever}×`],['Loss at the stop',`<span class="dn">−${t.loss} USDT</span> <span class="mu">${t.lossPct} of account</span>`],['Gain at both targets',`<span class="up">+${t.gain} USDT</span>`],['Reward to risk',`1 : ${t.rr}`]])}
<div style="font-size:12.5px;line-height:1.45;color:var(--text-secondary)">${t.why}</div><button data-tier="${t.key}">Place the ${t.name.toLowerCase()} plan on the demo account ↗</button></div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Position plan · ${d.instId} · as of ${d.asof}</div><div class="big">${d.head}</div><div class="sub">${d.bias}</div></div>
<div class="g" style="grid-template-columns:minmax(0,1.6fr) minmax(0,1fr);margin-bottom:10px"><div class="card"><div class="row" style="justify-content:space-between;align-items:baseline"><span style="font-size:14px;font-weight:500">Signal scorecard</span><span><span class="v n ${cl(d.score)}" style="font-size:26px">${d.score>0?'+':''}${d.score}</span> <span class="sub">${d.scoreLabel}</span></span></div>
<div style="position:relative;height:10px;border-radius:5px;margin:10px 0 4px;background:linear-gradient(90deg,var(--dn) 0,var(--dns) 35%,var(--surface-0) 35%,var(--surface-0) 65%,var(--ups) 65%,var(--up) 100%)"><span style="position:absolute;left:calc(${m}% - 2px);top:-4px;width:4px;height:18px;border-radius:2px;background:var(--text-primary)"></span></div><div class="row sub" style="justify-content:space-between;font-size:11px"><span>−100 short</span><span>−30</span><span>wait</span><span>+30</span><span>long +100</span></div>
<table class="rt" style="width:100%;border-collapse:collapse;margin-top:8px"><tr><th>Signal</th><th>Reading</th><th class="n">Weight</th><th class="n">Points</th></tr>${d.signals.map(s=>`<tr><td style="font-weight:500;white-space:nowrap">${s[0]}</td><td style="color:var(--text-secondary)">${s[1]}</td><td class="n mu">${s[2]}</td><td class="n"><span class="p ${s[3]>0?'u':s[3]<0?'d':''}">${s[3]>0?'+':''}${s[3]}</span></td></tr>`).join('')}</table></div>
<div class="card rc"><div class="row" style="justify-content:space-between;align-items:baseline"><span style="font-size:14px;font-weight:500">Risk</span><span><span class="v n" style="font-size:26px">${d.risk}</span> <span class="sub">of 10</span></span></div><div class="bar">${Array.from({length:10},(_,i)=>`<span style="flex:1;background:${i<d.risk?(d.risk>=7?'var(--dn)':d.risk>=4?'var(--am)':'var(--up)'):'var(--surface-0)'}"></span>`).join('')}</div>
${d.risks.map(r=>`<div class="fl"><span class="dot" style="background:var(--am)"></span><span>${r}</span></div>`).join('')}<div><h4>Plan is wrong if</h4><div style="font-size:13px;line-height:1.45;margin-top:3px">${d.invalid}</div></div><div>${kv(d.levels)}</div></div></div>
<div class="lbl" style="margin:0 0 6px 2px">${d.tiersLabel}</div><div class="g" style="grid-template-columns:repeat(auto-fit,minmax(215px,1fr));margin-bottom:10px">${d.tiers.map(tier).join('')}</div><div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-tier]').forEach(b=>{const t=d.tiers.find(x=>x.key==b.dataset.tier);b.onclick=()=>window.sendPrompt&&sendPrompt(`Place the ${t.name.toLowerCase()} ${d.ccy} plan on the demo account.`)})}
function tapeRow(t){const C={L:'var(--up)',C:'var(--ups)',S:'var(--dn)',X:'var(--dns)',N:'var(--surface-0)'},T={L:'price up, OI up — longs opening',C:'price up, OI down — shorts covering',S:'price down, OI up — shorts opening',X:'price down, OI down — longs closing',N:'quiet hour'};
return `<div style="display:flex;gap:2px" role="img" aria-label="Hour-by-hour positioning, last 24 hours">${t.split('').map((k,i)=>`<span title="${t.length-i}h ago · ${T[k]}" style="flex:1;height:12px;border-radius:2px;background:${C[k]};${k=='C'?'box-shadow:inset 0 0 0 1px var(--up)':k=='X'?'box-shadow:inset 0 0 0 1px var(--dn)':''}"></span>`).join('')}</div>`}
function tfGrid(tf){const bg=(v,vol)=>{const a=vol?Math.min(1,Math.max(0,(v-1)/3)):Math.min(1,Math.abs(v)/12);return vol?`rgba(42,120,214,${(.06+a*.3).toFixed(2)})`:v>=0?`rgba(15,157,106,${(.06+a*.34).toFixed(2)})`:`rgba(224,51,76,${(.06+a*.34).toFixed(2)})`};
return `<table style="width:100%;border-collapse:separate;border-spacing:3px;font-size:12px"><tr><th style="border:0;padding:0"></th>${['1h','4h','24h'].map(h=>`<th style="border:0;padding:0 0 1px;text-align:center;font-size:11px">${h}</th>`).join('')}</tr>${tf.map((r,i)=>`<tr><td style="border:0;padding:0 4px 0 0;color:var(--text-muted);font-size:11px;white-space:nowrap">${r[0]}</td>${r.slice(1).map(v=>`<td class="n" style="border:0;text-align:center;border-radius:5px;padding:5px 2px;font-weight:500;background:${bg(v,i==2)}">${i==2?v.toFixed(1)+'×':sg(v)}</td>`).join('')}</tr>`).join('')}</table>`}
function meter(m){const c=m[2]=='r'?'var(--dn)':m[2]=='a'?'var(--am)':m[2]=='g'?'var(--up)':'var(--nt)';
return `<div><div class="row" style="justify-content:space-between;gap:4px;flex-wrap:nowrap"><span class="lbl" style="font-size:11px;white-space:nowrap">${m[0]}</span><span class="n" style="font-size:12px;font-weight:500;color:${m[2]=='r'?'var(--dn)':'var(--text-primary)'};white-space:nowrap">${m[1]}</span></div><div style="position:relative;height:4px;border-radius:2px;background:var(--surface-0);margin-top:4px">${m[3]==null?'':`<span style="position:absolute;left:calc(${(m[3]*100).toFixed(0)}% - 4px);top:-3px;width:8px;height:10px;border-radius:3px;background:${c}"></span>`}</div></div>`}
function duoLv(a,b,lv){const W=300,H=112,X0=40,X1=258,T=20,B=108,lo=Math.min(...a,lv.go,lv.stop),hi=Math.max(...a,lv.go,lv.stop),rg=hi-lo||1,Y=v=>T+(hi-v)/rg*(B-T),ol=Math.min(...b),oh=Math.max(...b),og=(oh-ol)||1,YO=v=>B-(v-ol)/og*(B-T)*.85,X=i=>X0+i/(a.length-1)*(X1-X0),gc=lv.side=='short'?'var(--dn)':lv.side=='long'?'var(--up)':'var(--text-muted)';
const fmt=v=>v>=1000?Math.round(v).toLocaleString('en-US'):v>=10?v.toFixed(2):v>=.01?v.toFixed(4):v.toPrecision(3),fo=v=>v>=1000?'$'+(v/1000).toFixed(2)+'B':'$'+Math.round(v)+'M';
let s=`<text x="${X0}" y="11" font-size="10.5" fill="var(--text-secondary)"><tspan fill="var(--bl)" font-weight="500">▮</tspan> OI (left)   <tspan fill="var(--am)" font-weight="500">━</tspan> Price (right) · 3 days</text>`;
[0,.5,1].forEach(t=>{const v=ol+og*t,y=YO(v);s+=`<line x1="${X0}" y1="${y.toFixed(1)}" x2="${X1}" y2="${y.toFixed(1)}" stroke="var(--border)"/><text x="${X0-3}" y="${(y+3).toFixed(1)}" font-size="9.5" text-anchor="end" fill="var(--bl)">${fo(v)}</text>`});
[0,.5,1].forEach(t=>{const v=lo+rg*t;s+=`<text x="${X1+3}" y="${(Y(v)+3).toFixed(1)}" font-size="9.5" fill="var(--am)">${fmt(v)}</text>`});
const bp=b.map((v,i)=>X(i*(a.length-1)/(b.length-1)).toFixed(1)+','+YO(v).toFixed(1)).join(' ');
s+=`<polygon fill="var(--bl)" opacity=".14" points="${X0},${B} ${bp} ${X1},${B}"/><polyline fill="none" stroke="var(--bl)" stroke-width="1.5" stroke-linejoin="round" points="${bp}"/>`;
s+=`<line x1="${X0}" y1="${Y(lv.go).toFixed(1)}" x2="${X1}" y2="${Y(lv.go).toFixed(1)}" stroke="${gc}" stroke-width="1.3" stroke-dasharray="5 3"/><line x1="${X0}" y1="${Y(lv.stop).toFixed(1)}" x2="${X1}" y2="${Y(lv.stop).toFixed(1)}" stroke="var(--text-muted)" stroke-width="1" stroke-dasharray="2 3"/>`;
s+=`<polyline fill="none" stroke="var(--am)" stroke-width="1.8" stroke-linejoin="round" points="${a.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).join(' ')}"/>`;
return `<svg width="100%" viewBox="0 0 ${W} ${H}" role="img" aria-label="Open interest (left axis) and price (right axis) over the last three days, with the entry-trigger and setup-fails levels" style="display:block">${s}</svg>`}
function radar(el,d){rcss();el.classList.add('atk');
const SP={1:['vw','Long setup'],2:['vr','Short setup'],3:['vn','No trade']},ar=s=>s>0?'<span class="up">▲</span>':s<0?'<span class="dn">▼</span>':'<span class="mu">·</span>';
const smBar=m=>{if(!m)return `<div class="row" style="justify-content:space-between"><span class="lbl" style="font-size:11px">Smart money</span><span class="sub">no position among the top 100</span></div>`;const t=m.l+m.s||1;
return `<div><div class="row" style="justify-content:space-between;flex-wrap:nowrap"><span class="lbl" style="font-size:11px">Smart money</span><span class="n" style="font-size:13px;font-weight:500">${m.net}</span></div><div style="display:flex;height:16px;border-radius:4px;overflow:hidden;gap:2px;margin:4px 0 3px"><span class="n" style="width:${(m.l/t*100).toFixed(0)}%;min-width:44px;background:var(--ups);color:var(--up);font-size:11px;line-height:16px;padding:0 5px;white-space:nowrap">${m.lS} long</span><span class="n" style="flex:1;min-width:48px;background:var(--dns);color:var(--dn);font-size:11px;line-height:16px;padding:0 5px;text-align:right;white-space:nowrap">${m.sS} short</span></div><div class="sub" style="font-size:11px">${m.sub}</div></div>`};
const card=c=>`<div class="card rc" style="gap:10px;${c.k==1?'border:1.5px solid var(--up)':c.k==2?'border:1.5px solid var(--dn)':''}"><div class="row" style="justify-content:space-between;flex-wrap:nowrap"><span class="row" style="gap:6px"><span style="font-size:20px;font-weight:500">${c.ccy}</span><span class="chip">${c.theme}</span></span><span class="vd ${SP[c.k][0]}">${SP[c.k][1]}${c.k<3?' · '+c.conv:''}</span></div>
<div class="row" style="justify-content:space-between;align-items:baseline"><span class="row" style="align-items:baseline;gap:8px"><span class="v n">${c.lastS}</span><span class="n ${cl(c.chg24)}" style="font-size:14px;font-weight:500">${sg(c.chg24)}</span></span><span class="p">${c.stage}</span></div>
<div style="font-size:13.5px;line-height:1.35;font-weight:500">${c.tag}</div>
<div class="g" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:6px">${c.abs.map(a=>`<div style="background:var(--surface-0);border-radius:8px;padding:6px 8px;min-width:0"><div class="lbl" style="font-size:11px;white-space:nowrap">${a[0]}</div><div class="n" style="font-size:15px;font-weight:500;white-space:nowrap">${a[1]}</div><div class="sub n" style="font-size:11px;white-space:nowrap">${a[2]}</div>${a[3]&&a[3].length>1?`<div title="Mentions per 4 hours, last 48 hours" style="display:flex;align-items:flex-end;gap:1.5px;height:16px;margin-top:4px">${a[3].map((v,i,A)=>`<span style="flex:1;border-radius:1px;background:var(--bl);opacity:${i>=A.length-2?1:.45};height:${Math.max(8,v/Math.max(...A,1)*100).toFixed(0)}%"></span>`).join('')}</div>`:''}</div>`).join('')}</div>
<div>${duoLv(c.px,c.oi,c.lv)}<div class="row n" style="justify-content:space-between;font-size:12px;margin-top:5px">${c.lv.side=='long'?`<span><span class="up" style="font-weight:500">Enter long above ${c.lv.goS}</span></span><span class="mu">setup fails below ${c.lv.stopS}</span>`:c.lv.side=='short'?`<span><span class="dn" style="font-weight:500">Enter short below ${c.lv.goS}</span></span><span class="mu">setup fails above ${c.lv.stopS}</span>`:`<span class="mu">12h range ${c.lv.stopS} – ${c.lv.goS}</span>`}</div></div>
${tfGrid(c.tf)}
${c.pos?`<div><div class="lbl" style="font-size:11px;margin-bottom:4px">Who is long · who is short</div>${c.pos.map(r=>`<div style="margin-bottom:6px"><div class="row" style="justify-content:space-between;flex-wrap:nowrap;gap:6px;font-size:11.5px"><span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${r[0]}</span><span class="n mu" style="white-space:nowrap">${r[2]}</span></div>${r[1]==null?'':`<div style="display:flex;height:14px;border-radius:4px;overflow:hidden;gap:2px;margin-top:3px"><span class="n" style="width:${r[1]}%;min-width:30px;background:var(--ups);color:var(--up);font-size:11px;line-height:14px;padding:0 5px">${r[1]}%</span><span class="n" style="flex:1;min-width:30px;background:var(--dns);color:var(--dn);font-size:11px;line-height:14px;padding:0 5px;text-align:right">${100-r[1]}%</span></div>`}</div>`).join('')}</div>`:smBar(c.sm)}
${d.evidence?`<div><div class="lbl" style="font-size:11px;margin-bottom:2px">Evidence · ▲ votes long · ▼ votes short</div><div class="g" style="grid-template-columns:minmax(0,1fr);gap:0">${c.ev.map(e=>`<div class="row" style="justify-content:space-between;flex-wrap:nowrap;gap:6px;font-size:12px;padding:2px 0"><span style="white-space:nowrap">${ar(e[2])} ${e[0]}</span><span class="n mu" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${e[1]}</span></div>`).join('')}</div></div>`:''}
${c.driver?`<div style="font-size:12.5px;line-height:1.4;color:var(--text-secondary)">${c.driver}</div>`:''}${c.note?`<div class="row" style="gap:6px;font-size:12px;padding:5px 8px;border-radius:6px;background:rgba(237,161,0,.14)"><span class="dot" style="background:var(--am)"></span><span>${c.note}</span></div>`:''}${d.plan?`<button data-ccy="${c.ccy}" style="margin-top:auto">Design a position for ${c.ccy} ↗</button>`:''}</div>`;
const lg=(c,t,b)=>`<span class="row" style="gap:4px"><i style="width:12px;height:10px;border-radius:2px;background:${c};${b?'box-shadow:inset 0 0 0 1px '+b:''}"></i>${t}</span>`,dt=(c,t)=>`<span class="row" style="gap:4px"><span class="dot" style="background:${c}"></span>${t}</span>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;align-items:baseline;margin-bottom:8px"><span class="big" style="margin:0">${d.head}</span><span class="lbl">${d.scanned} alt perpetuals scanned on OKX · as of ${d.asof}</span></div>
<div class="row sub" style="margin-bottom:2px">${dt('var(--up)','long setup')}${dt('var(--dn)','short setup')}${dt('var(--am)','no trade')}${dt('var(--nt)','rest of the market')}<span>bubble = 24h volume</span></div>${radarMap(d.pts,d.thrX,d.thrY)}</div>
<div class="row sub" style="margin:0 2px 8px;gap:10px"><span style="color:var(--text-primary);font-weight:500">Candidates</span><span class="row" style="gap:4px"><i style="width:12px;height:0;border-top:1.5px dashed var(--text-secondary)"></i>entry trigger</span><span class="row" style="gap:4px"><i style="width:12px;height:0;border-top:1px dotted var(--text-muted)"></i>setup fails</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(290px,1fr));margin-bottom:10px">${d.cards.map(card).join('')}</div>${d.passed&&d.passed.length?`<div class="card" style="margin-bottom:10px;padding:10px 16px"><div class="row" style="gap:6px 14px"><span class="lbl">Checked and passed over</span>${d.passed.map(x=>`<span style="font-size:12.5px"><span class="dot" style="background:var(--am);margin-right:5px"></span><b style="font-weight:500">${x[0]}</b> <span class="mu">${x[1]}</span></span>`).join('')}</div></div>`:''}<div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-ccy]').forEach(b=>b.onclick=()=>window.sendPrompt&&sendPrompt(`Design a position for ${b.dataset.ccy}.`))}
function positionCard(el,d){rcss();el.classList.add('atk');const L=d.side=='long',c=L?'var(--up)':'var(--dn)',
row=(k,v,sub,cls)=>`<div style="display:flex;justify-content:space-between;align-items:baseline;gap:12px;padding:9px 0;border-top:0.5px solid var(--border)"><span style="font-size:13px;color:var(--text-secondary);white-space:nowrap">${k}</span><span style="text-align:right"><span class="n ${cls||''}" style="font-size:17px;font-weight:500">${v}</span>${sub?` <span class="n mu" style="font-size:12px;white-space:nowrap">${sub}</span>`:''}</span></div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Recommended ${d.ccy} ${d.side} position: entry ${d.entry}, stop ${d.stop}, targets ${d.tp1} and ${d.tp2}, ${d.contracts} contracts at ${d.lever}x</h2>
<div class="card" style="max-width:460px;margin:0 auto;border:1.5px solid ${c};padding:16px 18px"><div class="row" style="justify-content:space-between;flex-wrap:nowrap"><span class="row" style="gap:8px"><span style="font-size:22px;font-weight:500">${d.ccy}</span><span class="vd ${L?'vw':'vr'}" style="font-size:13px">${L?'Long':'Short'} · ${d.lever}× isolated</span></span><span class="sub n">conviction ${d.conv}</span></div>
<div class="sub n" style="margin:2px 0 8px">${d.instId} · price ${d.last} · as of ${d.asof}</div>
${row('Entry',d.entry,d.entryNote)}${row('Take profit 1 · half',d.tp1,d.tp1Pct,'up')}${row('Take profit 2 · half',d.tp2,d.tp2Pct,'up')}${row('Stop loss',d.stop,d.stopPct,'dn')}${row('Size',d.contracts+' contracts','≈ '+d.notional+' USDT · margin '+d.margin)}
<div class="g" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin:10px 0 12px">${[['Risk at stop','−'+d.loss+' USDT',d.lossPct+' of '+d.balance,'dn'],['Gain at targets','+'+d.gain+' USDT','both filled','up'],['Reward : risk',d.rr+' : 1','blended','']].map(a=>`<div style="background:var(--surface-0);border-radius:8px;padding:7px 9px;min-width:0"><div class="lbl" style="font-size:11px;white-space:nowrap">${a[0]}</div><div class="n ${a[3]}" style="font-size:15px;font-weight:500;white-space:nowrap">${a[1]}</div><div class="sub n" style="font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${a[2]}</div></div>`).join('')}</div>
<button data-go="1" style="width:100%;padding:11px;font-size:15px;font-weight:500">Confirm order ↗</button>
<details style="margin-top:10px"><summary style="cursor:pointer;font-size:12.5px;color:var(--text-secondary)">How these numbers were set</summary><div style="margin-top:6px">${d.notes.map(n=>`<div class="fl" style="padding:2px 0"><span style="flex:none;width:68px;color:var(--text-muted)">${n[0]}</span><span>${n[1]}</span></div>`).join('')}</div></details></div>`;
el.querySelector('button[data-go]').onclick=()=>window.sendPrompt&&sendPrompt(`Confirm — place the ${d.ccy} ${d.side} on the demo account.`)}
window.ATK={analysis,conclusion,dcdAnalysis,dcdConclusion,radarScan,radarCandidates,radarPlan,radar,positionCard,version:'2.0.0'};

})();
