/* ATK views — shared renderer for OKX Agent Trade Kit inline views. Loaded from a CDN; widgets stream data only. */
(function(){
const CSS=`
:root{--up:#0f9d6a;--dn:#e0334c;--ups:rgba(15,157,106,.12);--dns:rgba(224,51,76,.12);--bl:#2a78d6;--am:#eda100;--nt:#929292}
:root[data-mode="dark"]{--up:#1fc27c;--dn:#f5445c;--ups:rgba(31,194,124,.16);--dns:rgba(245,68,92,.16);--bl:#3987e5;--am:#c98500;--nt:#7a7a7a}
@media(prefers-color-scheme:dark){:root:not([data-mode="light"]){--up:#1fc27c;--dn:#f5445c;--ups:rgba(31,194,124,.16);--dns:rgba(245,68,92,.16);--bl:#3987e5;--am:#c98500;--nt:#7a7a7a}}
.atk .card{background:var(--surface-2);border:0.5px solid var(--border);border-radius:12px;padding:14px 16px;min-width:0}
.atk .lbl{font-size:12px;color:var(--text-muted)}.atk .sub{font-size:12px;color:var(--text-secondary)}
.atk .v{font-size:20px;font-weight:500;letter-spacing:-.01em;line-height:1.15}.atk .v2{font-size:16px;font-weight:500;line-height:1.3;margin-top:3px}
.atk .n{font-variant-numeric:tabular-nums}.atk .up{color:var(--up)}.atk .dn{color:var(--dn)}.atk .mu{color:var(--text-muted)}
.atk .chip{display:inline-flex;align-items:center;gap:6px;font-size:12px;padding:3px 10px;border-radius:999px;border:0.5px solid var(--border);color:var(--text-secondary);white-space:nowrap}
.atk .dot{width:7px;height:7px;border-radius:50%;display:inline-block}.atk .g{display:grid;gap:10px}.atk .row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.atk .p{display:inline-block;font-size:12px;padding:2px 8px;border-radius:6px;white-space:nowrap;background:var(--surface-0);color:var(--text-secondary)}.atk .p.u{background:var(--ups);color:var(--up)}.atk .p.d{background:var(--dns);color:var(--dn)}
.atk td,.atk th{padding:5px 6px;border-top:0.5px solid var(--border);text-align:left;font-weight:400}.atk th{border-top:0;color:var(--text-muted);font-weight:500}
.atk .bar{display:flex;height:10px;border-radius:5px;overflow:hidden;gap:2px}.atk svg text{font-family:inherit}
.atk .ev{display:flex;gap:10px;padding:6px 0;border-top:0.5px solid var(--border);font-size:13px}.atk .ev .dot{margin-top:6px;flex:none}
.atk .kv td:first-child{color:var(--text-secondary);white-space:nowrap}.atk .kv td:last-child{text-align:right}
.atk .opt{display:flex;flex-direction:column;gap:8px}.atk .opt button{margin-top:auto}`;
function css(){if(!document.getElementById('atk-css')){const s=document.createElement('style');s.id='atk-css';s.textContent=CSS;document.head.appendChild(s)}}
const f0=x=>Math.round(x).toLocaleString('en-US'),pc=(x,d=1)=>(x>0?'+':'')+x.toFixed(d)+'%',cl=x=>x>0?'up':x<0?'dn':'mu',dotc=k=>k=='u'?'var(--up)':k=='d'?'var(--dn)':'var(--nt)';
const pill=(v,t)=>`<span class="p ${v>0?'u':v<0?'d':''}">${v>0?'+':''}${v} · ${t}</span>`;
const sv=(h,b,lab)=>`<svg width="100%" viewBox="0 0 300 ${h}" preserveAspectRatio="none" role="img" aria-label="${lab||'sparkline'}" style="display:block;height:${h}px">${b}</svg>`;
function bars(a){const m=Math.max(...a.map(Math.abs))||1,w=300/a.length;return sv(56,`<line x1="0" y1="28" x2="300" y2="28" stroke="var(--border-strong)"/>`+a.map((v,i)=>{const h=Math.abs(v)/m*26;return `<rect x="${i*w+1}" y="${v>=0?28-h:28}" width="${Math.max(1,w-2)}" height="${Math.max(1,h)}" fill="${v>=0?'var(--up)':'var(--dn)'}"/>`}).join(''))}
function line(a,c,ref){const all=ref==null?a:a.concat([ref]),lo=Math.min(...all),hi=Math.max(...all),rg=hi-lo||1,px=i=>2+i/(a.length-1)*296,py=v=>54-(v-lo)/rg*52;
return sv(56,(ref==null?'':`<line x1="0" y1="${py(ref)}" x2="300" y2="${py(ref)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/>`)+`<polyline fill="none" stroke="${c}" stroke-width="2" stroke-linejoin="round" vector-effect="non-scaling-stroke" points="${a.map((v,i)=>px(i)+','+py(v)).join(' ')}"/><circle cx="${px(a.length-1)}" cy="${py(a[a.length-1])}" r="3.5" fill="${c}" stroke="var(--surface-2)" stroke-width="1.5"/>`)}
function candles(K,L,DT,LV,last){const X0=6,X1=596,Y0=14,Y1=236,V0=250,V1=296,n=K.length,st=(X1-X0)/n,bw=Math.max(2,st*.62);
let lo=Math.min(...K.map(k=>k[2]),...LV.map(l=>l[1])),hi=Math.max(...K.map(k=>k[1]),...LV.map(l=>l[1]));const pd=(hi-lo)*.05;lo-=pd;hi+=pd;
const Y=p=>Y1-(p-lo)/(hi-lo)*(Y1-Y0),X=i=>X0+st*(i+.5),vm=Math.max(...K.map(k=>k[4]))||1;let s='';
for(let t=Math.ceil(lo/2000)*2000;t<hi;t+=2000)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="var(--border)"/><text x="602" y="${Y(t)+4}" font-size="11" fill="var(--text-muted)">${t/1000}k</text>`;
const pl=(a,c,d)=>`<polyline fill="none" stroke="${c}" stroke-width="${d?1:1.5}" ${d?'stroke-dasharray="3 3" opacity=".7"':''} stroke-linejoin="round" points="${a.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).join(' ')}"/>`;
s+=`<defs><clipPath id="atkcp"><rect x="${X0}" y="${Y0-2}" width="${X1-X0}" height="${Y1-Y0+4}"/></clipPath></defs><g clip-path="url(#atkcp)"><polygon fill="var(--text-muted)" opacity=".06" points="${L.bu.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).join(' ')} ${L.bl.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).reverse().join(' ')}"/>${pl(L.bu,'var(--text-muted)',1)}${pl(L.bl,'var(--text-muted)',1)}</g>`;
K.forEach((k,i)=>{const c=k[3]>=k[0]?'var(--up)':'var(--dn)',x=X(i),t=Y(Math.max(k[0],k[3])),b=Y(Math.min(k[0],k[3])),vh=k[4]/vm*(V1-V0);
s+=`<line x1="${x}" y1="${Y(k[1])}" x2="${x}" y2="${Y(k[2])}" stroke="${c}"/><rect x="${x-bw/2}" y="${t}" width="${bw}" height="${Math.max(1,b-t)}" fill="${c}"/><rect x="${x-bw/2}" y="${V1-vh}" width="${bw}" height="${vh}" fill="${c}" opacity=".45"/>`});
s+=pl(L.e20,'var(--bl)')+pl(L.s50,'var(--am)');
LV.forEach(l=>{const c=l[0]=='S'?'var(--up)':'var(--dn)',y=Y(l[1]);s+=`<line x1="${X0}" y1="${y}" x2="${X1}" y2="${y}" stroke="${c}" stroke-dasharray="6 4" opacity=".8"/><text x="10" y="${y-3}" font-size="11" fill="${c}">${l[0]} ${f0(l[1])}</text>`});
const yp=Y(last);s+=`<rect x="598" y="${yp-9}" width="78" height="18" rx="4" fill="var(--text-primary)"/><text x="637" y="${yp+4}" font-size="11" font-weight="500" text-anchor="middle" fill="var(--surface-2)">${f0(last)}</text>`;
for(let i=0;i<n;i+=15)s+=`<text x="${X(i)}" y="306" font-size="11" text-anchor="${i?'middle':'start'}" fill="var(--text-muted)">${DT[i]}</text>`;
return `<svg width="100%" viewBox="0 0 680 306" role="img" aria-label="Daily candlestick chart, last ${n} days" style="display:block;overflow:visible">${s}</svg>`}
function gauge(val){const cx=110,cy=116,r=94,A=(a0,a1,c,o)=>{const p=a=>[cx+r*Math.cos(Math.PI*(1-a)),cy-r*Math.sin(Math.PI*(1-a))],[x0,y0]=p(a0),[x1,y1]=p(a1);return `<path d="M${x0} ${y0} A${r} ${r} 0 0 1 ${x1} ${y1}" fill="none" stroke="${c}" stroke-width="12" opacity="${o}"/>`};
let g=[[0,.2,'var(--up)',.9],[.2,.4,'var(--up)',.5],[.4,.6,'var(--nt)',.5],[.6,.8,'var(--dn)',.5],[.8,1,'var(--dn)',.9]].map(z=>A(z[0]+.004,z[1]-.004,z[2],z[3])).join('');
const an=Math.PI*(1-val/100);g+=`<line x1="${cx}" y1="${cy}" x2="${cx+(r-2)*Math.cos(an)}" y2="${cy-(r-2)*Math.sin(an)}" stroke="var(--text-primary)" stroke-width="2.5" stroke-linecap="round"/><circle cx="${cx}" cy="${cy}" r="5" fill="var(--text-primary)"/><text x="${cx}" y="${cy-30}" text-anchor="middle" font-size="34" font-weight="500" fill="var(--text-primary)">${val}</text><text x="14" y="132" font-size="11" fill="var(--text-muted)">0 · value</text><text x="206" y="132" text-anchor="end" font-size="11" fill="var(--text-muted)">mania · 100</text>`;
return `<svg width="220" height="132" viewBox="0 0 220 132" role="img" aria-label="Cycle temperature gauge ${val} of 100">${g}</svg>`}
function ivcurve(IV,EX,HV){const lo=Math.min(...IV,HV)-3,hi=Math.max(...IV,HV)+3,px=i=>24+i/(IV.length-1)*252,py=v=>70-(v-lo)/(hi-lo)*58;
return `<svg width="100%" viewBox="0 0 300 96" role="img" aria-label="ATM implied vol by expiry vs realized vol" style="display:block;height:96px"><line x1="14" y1="${py(HV)}" x2="290" y2="${py(HV)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/><text x="290" y="${py(HV)-4}" font-size="10" text-anchor="end" fill="var(--text-muted)">HV30 ${HV.toFixed(0)}%</text><polyline fill="none" stroke="var(--am)" stroke-width="2" stroke-linejoin="round" points="${IV.map((v,i)=>px(i)+','+py(v)).join(' ')}"/>`+IV.map((v,i)=>`<circle cx="${px(i)}" cy="${py(v)}" r="3.5" fill="var(--am)" stroke="var(--surface-2)" stroke-width="1.5"/><text x="${px(i)}" y="${py(v)-8}" font-size="10" text-anchor="middle" fill="var(--text-secondary)">${v.toFixed(0)}</text><text x="${px(i)}" y="90" font-size="10" text-anchor="middle" fill="var(--text-muted)">${EX[i]}</text>`).join('')+'</svg>'}
function ladder(LV){const lo=LV[3][0]-600,hi=LV[0][0]+600,Y=p=>22+(hi-p)/(hi-lo)*206,C={u:'var(--up)',d:'var(--dn)',e:'var(--text-primary)'};
let s=`<rect x="70" y="${Y(LV[0][0])}" width="60" height="${Y(LV[2][0])-Y(LV[0][0])}" fill="var(--ups)"/><rect x="70" y="${Y(LV[2][0])}" width="60" height="${Y(LV[3][0])-Y(LV[2][0])}" fill="var(--dns)"/><text x="100" y="${(Y(LV[1][0])+Y(LV[2][0]))/2+4}" text-anchor="middle" font-size="12" font-weight="500" fill="var(--up)">+${((LV[1][0]/LV[2][0]-1)*100).toFixed(1)}%</text><text x="100" y="${(Y(LV[3][0])+Y(LV[2][0]))/2+4}" text-anchor="middle" font-size="12" font-weight="500" fill="var(--dn)">−${((1-LV[3][0]/LV[2][0])*100).toFixed(1)}%</text>`;
LV.forEach(l=>{const y=Y(l[0]);s+=`<line x1="60" y1="${y}" x2="140" y2="${y}" stroke="${C[l[2]]}" stroke-width="1.5"/><text x="150" y="${y+4}" font-size="12" font-weight="500" fill="${C[l[2]]}">${f0(l[0])}</text><text x="210" y="${y+4}" font-size="11" fill="var(--text-muted)">${l[1]}</text>`});
return `<svg width="100%" viewBox="0 0 320 250" role="img" aria-label="Trade ladder" style="display:block">${s}</svg>`}
const kv=rows=>`<table class="kv" style="width:100%;border-collapse:collapse;font-size:12px">${rows.map(r=>`<tr><td>${r[0]}</td><td class="n">${r[1]}</td></tr>`).join('')}</table>`;

function analysis(el,d){css();el.classList.add('atk');const k=d.kpi,m=d.mx,dv=d.deriv,sn=d.sent;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${d.sym} analysis at ${d.asof}: price ${f0(k.price)} USDT, cycle score ${d.cycle} of 100 (${d.zone}), signal matrix, derivatives and sentiment.</h2>
<div class="row" style="justify-content:space-between;margin-bottom:12px"><div class="row"><span class="chip"><span class="dot" style="background:var(--up)"></span>Live · OKX</span><span class="chip">${d.inst}</span></div><span class="sub n">as of ${d.asof}</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(140px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">Last price</div><div class="v n">${f0(k.price)} <span class="sub">USDT</span></div><div class="sub n ${cl(k.chg24)}">${pc(k.chg24,2)} 24h</div></div>
<div class="card"><div class="lbl">24h range</div><div class="v2 n">${f0(k.lo24)}–${f0(k.hi24)}</div><div class="sub n">ATR14 ${f0(k.atr)} · ${(k.atr/k.price*100).toFixed(1)}% of price</div></div>
<div class="card"><div class="lbl">7d / 30d change</div><div class="v2 n"><span class="${cl(k.chg7)}">${pc(k.chg7)}</span> <span class="mu">/</span> <span class="${cl(k.chg30)}">${pc(k.chg30)}</span></div><div class="sub n">30d realized vol ${k.hv30.toFixed(0)}%</div></div>
<div class="card"><div class="lbl">Perp open interest</div><div class="v n">$${(k.oi/1e9).toFixed(2)}B</div><div class="sub n">funding ${(k.fr*100).toFixed(4)}% / 8h</div></div></div>
<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">Daily candles · ${d.K.length} days</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--bl)"></i>EMA20</span><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--am)"></i>SMA50</span><span class="row" style="gap:4px"><i style="width:14px;border-top:1px dashed var(--text-muted)"></i>BB 20,2</span><span class="row" style="gap:4px"><i style="width:14px;border-top:1px dashed var(--dn)"></i>S / R</span></span></div>${candles(d.K,d.L,d.DT,d.LV,k.price)}</div>
<div class="g" style="grid-template-columns:minmax(0,240px) minmax(0,1fr);margin:10px 0">
<div class="card" style="display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center"><div class="lbl" style="align-self:flex-start">Cycle temperature · 3-pillar composite</div>${gauge(d.cycle)}<div style="font-size:14px;font-weight:500;margin-top:4px">${d.zone}</div><div class="sub">${d.action}</div></div>
<div class="card"><div class="lbl" style="margin-bottom:10px">Pillars · 0 = cold, 100 = overheated</div>${d.pillars.map(p=>`<div style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span style="font-size:13px">${p[0]} <span class="mu">· ${p[1]}%</span></span><span class="n" style="font-size:14px;font-weight:500">${p[2]}</span></div><div style="height:8px;border-radius:4px;background:var(--surface-0);border:0.5px solid var(--border);overflow:hidden"><div style="height:100%;width:${p[2]}%;background:${p[2]<40?'var(--up)':p[2]>60?'var(--dn)':'var(--nt)'};border-radius:4px"></div></div><div class="sub n" style="margin-top:4px">${p[3]}</div></div>`).join('')}</div></div>
<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">Signal matrix · price-volume scoring per timeframe</span><span class="sub">weights 1D 50% · 4H 30% · 1H 20% → <b class="n" style="font-weight:500;color:var(--text-primary)">${m.total}/100</b></span></div>
<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px;table-layout:fixed"><colgroup><col style="width:88px"><col><col><col></colgroup><tr><th>Factor</th>${m.H.map(h=>`<th>${h}</th>`).join('')}</tr>${m.M.map(r=>`<tr><td style="color:var(--text-secondary)">${r[0]}</td>${r.slice(1).map(c=>`<td>${pill(c[0],c[1])}</td>`).join('')}</tr>`).join('')}<tr><td style="font-weight:500;border-top-color:var(--border-strong)">Score</td>${m.S.map(s=>`<td style="border-top-color:var(--border-strong)"><span class="n" style="font-weight:500">${s[0]}</span><span class="mu"> /100 · raw ${s[1]>0?'+':''}${s[1]}</span></td>`).join('')}</tr></table></div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin:10px 0">
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Funding rate · last 30 settlements</span><span class="n ${cl(k.fr)}" style="font-size:13px;font-weight:500">${(k.fr*100).toFixed(4)}%</span></div><div class="sub n" style="margin-bottom:6px">30-settlement avg ${dv.fravg.toFixed(4)}% · baseline 0.0100%</div>${bars(dv.F)}</div>
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Perp open interest · 30 days</span><span class="n" style="font-size:13px;font-weight:500">$${dv.OI[dv.OI.length-1].toFixed(2)}B</span></div><div class="sub n" style="margin-bottom:6px">1d <span class="${cl(dv.oi1d)}">${pc(dv.oi1d)}</span> · 30d <span class="${cl(dv.oi30d)}">${pc(dv.oi30d)}</span></div>${line(dv.OI,'var(--bl)')}</div>
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Top-trader long/short · 30 days</span><span class="n" style="font-size:13px;font-weight:500">${dv.lsr.toFixed(2)}</span></div><div class="sub n" style="margin-bottom:6px">long ${dv.longp}% · short ${100-dv.longp}% · 1.00 = balanced</div>${line(dv.LS,dv.lsr>1?'var(--up)':'var(--dn)',1)}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">
<div class="card"><div class="lbl">Options · ATM implied vol term structure</div><div class="sub n" style="margin-bottom:4px">front IV ${dv.IV[1].toFixed(0)}% vs HV30 ${k.hv30.toFixed(0)}% · 25d skew ${(dv.skew>0?'+':'')+dv.skew.toFixed(1)} vol (${dv.skew>0.5?'puts richer':dv.skew<-0.5?'calls richer':'flat'})</div>${ivcurve(dv.IV,dv.EX,k.hv30)}</div>
<div class="card"><div class="lbl">Options open interest · put / call</div><div class="v n" style="margin:4px 0 6px">${dv.pcr.toFixed(2)} <span class="sub">put/call ratio</span></div><div class="bar" style="height:12px"><div style="width:${dv.putp}%;background:var(--dn)"></div><div style="flex:1;background:var(--up)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:6px"><span>puts ${dv.putp}%</span><span>calls ${100-dv.putp}%</span></div>
<div class="lbl" style="margin-top:14px">Fear &amp; Greed · social sentiment (24h)</div><div class="row" style="gap:12px;margin-top:6px"><span class="n" style="font-size:26px;font-weight:500;color:${sn.fng<40?'var(--dn)':sn.fng>60?'var(--up)':'var(--nt)'}">${sn.fng}</span><span class="sub">${sn.fngLabel} · yesterday ${sn.fngPrev}</span></div>
<div class="bar" style="margin-top:8px"><div style="width:${sn.bull}%;background:var(--up)"></div><div style="width:${100-sn.bull-sn.bear}%;background:var(--nt)"></div><div style="flex:1;background:var(--dn)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:4px"><span>bullish ${sn.bull}%</span><span>neutral ${100-sn.bull-sn.bear}%</span><span>bearish ${sn.bear}%</span></div></div></div>`}

function conclusion(el,d){css();el.classList.add('atk');const t=d.tiles,ob=d.ob;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Conclusion: ${d.head}. Verdict ${t.verdict}, signal ${t.signal} of 100; entry ${f0(d.LV[2][0])}, stop ${f0(d.LV[3][0])}, targets ${f0(d.LV[1][0])} and ${f0(d.LV[0][0])}; options: ${d.opts.map(o=>o.kind).join(', ')}.</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Market direction · conclusion</div><div style="font-size:18px;font-weight:500;line-height:1.25;margin:4px 0 2px">${d.head}</div><div class="sub" style="margin-bottom:6px">${d.bias} · as of ${d.asof}</div>${d.evidence.map(e=>`<div class="ev"><span class="dot" style="background:${dotc(e[2])}"></span><span><span style="color:var(--text-secondary)">${e[0]} · </span>${e[1]}</span></div>`).join('')}</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(150px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">Verdict</div><div style="font-size:18px;font-weight:500;line-height:1.2;margin-top:2px">${t.verdict}</div><div class="sub">${t.passed} of 3 entry conditions met</div></div>
<div class="card"><div class="lbl">Long signal quality</div><div class="v n">${t.signal}<span class="sub"> /100</span> <span class="p" style="font-size:13px;font-weight:500;color:${t.gradeColor}">grade ${t.grade}</span></div><div class="sub n">${t.sub}</div></div>
<div class="card"><div class="lbl">Risk / reward</div><div class="v n">${t.rr1.toFixed(2)} <span class="sub">to T1</span></div><div class="sub n">${t.rr2.toFixed(2)} to T2 · risk ${f0(t.risk)} USDT per ${d.base}</div></div>
<div class="card"><div class="lbl">Sizing tier · cycle ${d.cycle}</div><div class="v n">≤ ${t.lever}</div><div class="sub">${t.size} of account per trade · stop ${t.stopw}</div></div></div>
<div class="g" style="grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);margin-bottom:10px">
<div class="card"><div class="lbl" style="margin-bottom:4px">Price ladder · USDT</div>${ladder(d.LV)}</div>
<div class="card"><div class="lbl" style="margin-bottom:2px">Entry conditions · all three required</div>${d.CK.map(c=>`<div style="display:flex;gap:10px;align-items:flex-start;padding:8px 0;border-top:0.5px solid var(--border)"><span style="flex:none;width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:${c[1]?'var(--ups)':'var(--dns)'};color:${c[1]?'var(--up)':'var(--dn)'};font-size:14px;font-weight:500">${c[1]?'✓':'✕'}</span><span><div style="font-size:13px;font-weight:500">${c[0]}</div><div class="sub n">${c[2]}</div></span></div>`).join('')}
<div class="lbl" style="margin-top:12px;margin-bottom:6px">Patterns &amp; divergences detected</div><div style="line-height:2">${d.PT.map(p=>`<span class="p ${p[1]=='u'?'u':p[1]=='d'?'d':''}">${p[0]}</span> `).join('')}</div>
<div class="lbl" style="margin-top:12px;margin-bottom:4px">Order book · top 50 levels</div><div class="bar"><div style="width:${ob.bidp}%;background:var(--up)"></div><div style="flex:1;background:var(--dn)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:4px"><span>bids ${f0(ob.bid)} ${d.base}</span><span>imbalance ${(ob.imb>0?'+':'')+ob.imb}%</span><span>asks ${f0(ob.ask)} ${d.base}</span></div></div></div>
<div class="lbl" style="margin:10px 0 6px 2px">Opening options · pick one, each button opens a preview (nothing is placed without confirmation)</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">${d.opts.map(o=>`<div class="card opt" style="${o.star?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span style="font-size:14px;font-weight:500"><span class="p" style="margin-right:6px">${o.tag}</span>${o.kind}</span>${o.star?'<span class="p u">best fit now</span>':''}</div><div class="sub">${o.fit}</div><div style="font-size:13px;line-height:1.45">${o.why}</div>${kv(o.rows)}<button data-cmd="${o.tag}">Preview option ${o.tag} ↗</button></div>`).join('')}</div>
<div class="sub" style="margin-top:10px">${d.foot}</div>`;
el.querySelectorAll('button[data-cmd]').forEach(b=>{const o=d.opts.find(x=>x.tag==b.dataset.cmd);b.onclick=()=>window.sendPrompt&&sendPrompt(`Preview option ${o.tag} (${o.kind}): \`${o.cmd}\`. Show me the preview and the exact risk in USDT — do NOT place it until I confirm.`)})}
window.ATK={analysis,conclusion,version:'1.0.0'};
})();
