/* ATK views — shared renderer for OKX Agent Trade Kit inline views. Loaded from a CDN; widgets stream data only. */
(function(){
const CSS=`
:root{--up:#0f9d6a;--dn:#e0334c;--ups:rgba(15,157,106,.12);--dns:rgba(224,51,76,.12);--bl:#2a78d6;--am:#eda100;--nt:#929292}
:root[data-mode="dark"]{--up:#1fc27c;--dn:#f5445c;--ups:rgba(31,194,124,.16);--dns:rgba(245,68,92,.16);--bl:#3987e5;--am:#c98500;--nt:#7a7a7a}
@media(prefers-color-scheme:dark){:root:not([data-mode="light"]){--up:#1fc27c;--dn:#f5445c;--ups:rgba(31,194,124,.16);--dns:rgba(245,68,92,.16);--bl:#3987e5;--am:#c98500;--nt:#7a7a7a}}
.atk .card{background:var(--surface-2);border:0.5px solid var(--border);border-radius:12px;padding:14px 16px;min-width:0}
.atk .lbl{font-size:12px;color:var(--text-muted)}.atk .sub{font-size:12px;color:var(--text-secondary)}
.atk .v{font-size:20px;font-weight:500;letter-spacing:-.01em;line-height:1.15}.atk .v2{font-size:16px;font-weight:500;line-height:1.3;margin-top:3px}
.atk .n{font-variant-numeric:tabular-nums}.atk .up{color:var(--up)}.atk .dn{color:var(--dn)}.atk .mu{color:var(--text-muted)}
.atk .chip{display:inline-flex;align-items:center;gap:6px;font-size:12px;padding:3px 10px;border-radius:999px;border:0.5px solid var(--border);color:var(--text-secondary);white-space:nowrap}
.atk .dot{width:7px;height:7px;border-radius:50%;display:inline-block}.atk .g{display:grid;gap:10px}.atk .row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.atk .p{display:inline-block;font-size:12px;padding:2px 8px;border-radius:6px;white-space:nowrap;background:var(--surface-0);color:var(--text-secondary)}.atk .p.u{background:var(--ups);color:var(--up)}.atk .p.d{background:var(--dns);color:var(--dn)}
.atk td,.atk th{padding:5px 6px;border-top:0.5px solid var(--border);text-align:left;font-weight:400}.atk th{border-top:0;color:var(--text-muted);font-weight:500}
.atk .bar{display:flex;height:10px;border-radius:5px;overflow:hidden;gap:2px}.atk svg text{font-family:inherit}
.atk .ev{display:flex;gap:10px;padding:6px 0;border-top:0.5px solid var(--border);font-size:13px}.atk .ev .dot{margin-top:6px;flex:none}
.atk .kv td:first-child{color:var(--text-secondary);white-space:nowrap}.atk .kv td:last-child{text-align:right}
.atk .opt{display:flex;flex-direction:column;gap:8px}.atk .opt button{margin-top:auto}`;
function css(){if(!document.getElementById('atk-css')){const s=document.createElement('style');s.id='atk-css';s.textContent=CSS;document.head.appendChild(s)}}
const f0=x=>Math.round(x).toLocaleString('en-US'),pc=(x,d=1)=>(x>0?'+':'')+x.toFixed(d)+'%',cl=x=>x>0?'up':x<0?'dn':'mu',dotc=k=>k=='u'?'var(--up)':k=='d'?'var(--dn)':'var(--nt)';
const pill=(v,t)=>`<span class="p ${v>0?'u':v<0?'d':''}">${v>0?'+':''}${v} · ${t}</span>`;
const sv=(h,b,lab)=>`<svg width="100%" viewBox="0 0 300 ${h}" preserveAspectRatio="none" role="img" aria-label="${lab||'sparkline'}" style="display:block;height:${h}px">${b}</svg>`;
function bars(a){const m=Math.max(...a.map(Math.abs))||1,w=300/a.length;return sv(56,`<line x1="0" y1="28" x2="300" y2="28" stroke="var(--border-strong)"/>`+a.map((v,i)=>{const h=Math.abs(v)/m*26;return `<rect x="${i*w+1}" y="${v>=0?28-h:28}" width="${Math.max(1,w-2)}" height="${Math.max(1,h)}" fill="${v>=0?'var(--up)':'var(--dn)'}"/>`}).join(''))}
function line(a,c,ref){const all=ref==null?a:a.concat([ref]),lo=Math.min(...all),hi=Math.max(...all),rg=hi-lo||1,px=i=>2+i/(a.length-1)*296,py=v=>54-(v-lo)/rg*52;
return sv(56,(ref==null?'':`<line x1="0" y1="${py(ref)}" x2="300" y2="${py(ref)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/>`)+`<polyline fill="none" stroke="${c}" stroke-width="2" stroke-linejoin="round" vector-effect="non-scaling-stroke" points="${a.map((v,i)=>px(i)+','+py(v)).join(' ')}"/><circle cx="${px(a.length-1)}" cy="${py(a[a.length-1])}" r="3.5" fill="${c}" stroke="var(--surface-2)" stroke-width="1.5"/>`)}
function candles(K,L,DT,LV,last){const X0=6,X1=596,Y0=14,Y1=236,V0=250,V1=296,n=K.length,st=(X1-X0)/n,bw=Math.max(2,st*.62);
let lo=Math.min(...K.map(k=>k[2]),...LV.map(l=>l[1])),hi=Math.max(...K.map(k=>k[1]),...LV.map(l=>l[1]));const pd=(hi-lo)*.05;lo-=pd;hi+=pd;
const Y=p=>Y1-(p-lo)/(hi-lo)*(Y1-Y0),X=i=>X0+st*(i+.5),vm=Math.max(...K.map(k=>k[4]))||1;let s='';
for(let t=Math.ceil(lo/2000)*2000;t<hi;t+=2000)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="var(--border)"/><text x="602" y="${Y(t)+4}" font-size="11" fill="var(--text-muted)">${t/1000}k</text>`;
const pl=(a,c,d)=>`<polyline fill="none" stroke="${c}" stroke-width="${d?1:1.5}" ${d?'stroke-dasharray="3 3" opacity=".7"':''} stroke-linejoin="round" points="${a.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).join(' ')}"/>`;
s+=`<defs><clipPath id="atkcp"><rect x="${X0}" y="${Y0-2}" width="${X1-X0}" height="${Y1-Y0+4}"/></clipPath></defs><g clip-path="url(#atkcp)"><polygon fill="var(--text-muted)" opacity=".06" points="${L.bu.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).join(' ')} ${L.bl.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).reverse().join(' ')}"/>${pl(L.bu,'var(--text-muted)',1)}${pl(L.bl,'var(--text-muted)',1)}</g>`;
K.forEach((k,i)=>{const c=k[3]>=k[0]?'var(--up)':'var(--dn)',x=X(i),t=Y(Math.max(k[0],k[3])),b=Y(Math.min(k[0],k[3])),vh=k[4]/vm*(V1-V0);
s+=`<line x1="${x}" y1="${Y(k[1])}" x2="${x}" y2="${Y(k[2])}" stroke="${c}"/><rect x="${x-bw/2}" y="${t}" width="${bw}" height="${Math.max(1,b-t)}" fill="${c}"/><rect x="${x-bw/2}" y="${V1-vh}" width="${bw}" height="${vh}" fill="${c}" opacity=".45"/>`});
s+=pl(L.e20,'var(--bl)')+pl(L.s50,'var(--am)');
LV.forEach(l=>{const c=l[0]=='S'?'var(--up)':'var(--dn)',y=Y(l[1]);s+=`<line x1="${X0}" y1="${y}" x2="${X1}" y2="${y}" stroke="${c}" stroke-dasharray="6 4" opacity=".8"/><text x="10" y="${y-3}" font-size="11" fill="${c}">${l[0]} ${f0(l[1])}</text>`});
const yp=Y(last);s+=`<rect x="598" y="${yp-9}" width="78" height="18" rx="4" fill="var(--text-primary)"/><text x="637" y="${yp+4}" font-size="11" font-weight="500" text-anchor="middle" fill="var(--surface-2)">${f0(last)}</text>`;
for(let i=0;i<n;i+=15)s+=`<text x="${X(i)}" y="306" font-size="11" text-anchor="${i?'middle':'start'}" fill="var(--text-muted)">${DT[i]}</text>`;
return `<svg width="100%" viewBox="0 0 680 306" role="img" aria-label="Daily candlestick chart, last ${n} days" style="display:block;overflow:visible">${s}</svg>`}
function gauge(val){const cx=110,cy=116,r=94,A=(a0,a1,c,o)=>{const p=a=>[cx+r*Math.cos(Math.PI*(1-a)),cy-r*Math.sin(Math.PI*(1-a))],[x0,y0]=p(a0),[x1,y1]=p(a1);return `<path d="M${x0} ${y0} A${r} ${r} 0 0 1 ${x1} ${y1}" fill="none" stroke="${c}" stroke-width="12" opacity="${o}"/>`};
let g=[[0,.2,'var(--up)',.9],[.2,.4,'var(--up)',.5],[.4,.6,'var(--nt)',.5],[.6,.8,'var(--dn)',.5],[.8,1,'var(--dn)',.9]].map(z=>A(z[0]+.004,z[1]-.004,z[2],z[3])).join('');
const an=Math.PI*(1-val/100);g+=`<line x1="${cx}" y1="${cy}" x2="${cx+(r-2)*Math.cos(an)}" y2="${cy-(r-2)*Math.sin(an)}" stroke="var(--text-primary)" stroke-width="2.5" stroke-linecap="round"/><circle cx="${cx}" cy="${cy}" r="5" fill="var(--text-primary)"/><text x="${cx}" y="${cy-30}" text-anchor="middle" font-size="34" font-weight="500" fill="var(--text-primary)">${val}</text><text x="14" y="132" font-size="11" fill="var(--text-muted)">0 · value</text><text x="206" y="132" text-anchor="end" font-size="11" fill="var(--text-muted)">mania · 100</text>`;
return `<svg width="220" height="132" viewBox="0 0 220 132" role="img" aria-label="Cycle temperature gauge ${val} of 100">${g}</svg>`}
function ivcurve(IV,EX,HV){const lo=Math.min(...IV,HV)-3,hi=Math.max(...IV,HV)+3,px=i=>24+i/(IV.length-1)*252,py=v=>70-(v-lo)/(hi-lo)*58;
return `<svg width="100%" viewBox="0 0 300 96" role="img" aria-label="ATM implied vol by expiry vs realized vol" style="display:block;height:96px"><line x1="14" y1="${py(HV)}" x2="290" y2="${py(HV)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/><text x="290" y="${py(HV)-4}" font-size="10" text-anchor="end" fill="var(--text-muted)">HV30 ${HV.toFixed(0)}%</text><polyline fill="none" stroke="var(--am)" stroke-width="2" stroke-linejoin="round" points="${IV.map((v,i)=>px(i)+','+py(v)).join(' ')}"/>`+IV.map((v,i)=>`<circle cx="${px(i)}" cy="${py(v)}" r="3.5" fill="var(--am)" stroke="var(--surface-2)" stroke-width="1.5"/><text x="${px(i)}" y="${py(v)-8}" font-size="10" text-anchor="middle" fill="var(--text-secondary)">${v.toFixed(0)}</text><text x="${px(i)}" y="90" font-size="10" text-anchor="middle" fill="var(--text-muted)">${EX[i]}</text>`).join('')+'</svg>'}
function ladder(LV){const lo=LV[3][0]-600,hi=LV[0][0]+600,Y=p=>22+(hi-p)/(hi-lo)*206,C={u:'var(--up)',d:'var(--dn)',e:'var(--text-primary)'};
let s=`<rect x="70" y="${Y(LV[0][0])}" width="60" height="${Y(LV[2][0])-Y(LV[0][0])}" fill="var(--ups)"/><rect x="70" y="${Y(LV[2][0])}" width="60" height="${Y(LV[3][0])-Y(LV[2][0])}" fill="var(--dns)"/><text x="100" y="${(Y(LV[1][0])+Y(LV[2][0]))/2+4}" text-anchor="middle" font-size="12" font-weight="500" fill="var(--up)">+${((LV[1][0]/LV[2][0]-1)*100).toFixed(1)}%</text><text x="100" y="${(Y(LV[3][0])+Y(LV[2][0]))/2+4}" text-anchor="middle" font-size="12" font-weight="500" fill="var(--dn)">−${((1-LV[3][0]/LV[2][0])*100).toFixed(1)}%</text>`;
LV.forEach(l=>{const y=Y(l[0]);s+=`<line x1="60" y1="${y}" x2="140" y2="${y}" stroke="${C[l[2]]}" stroke-width="1.5"/><text x="150" y="${y+4}" font-size="12" font-weight="500" fill="${C[l[2]]}">${f0(l[0])}</text><text x="210" y="${y+4}" font-size="11" fill="var(--text-muted)">${l[1]}</text>`});
return `<svg width="100%" viewBox="0 0 320 250" role="img" aria-label="Trade ladder" style="display:block">${s}</svg>`}
const kv=rows=>`<table class="kv" style="width:100%;border-collapse:collapse;font-size:12px">${rows.map(r=>`<tr><td>${r[0]}</td><td class="n">${r[1]}</td></tr>`).join('')}</table>`;

function analysis(el,d){css();el.classList.add('atk');const k=d.kpi,m=d.mx,dv=d.deriv,sn=d.sent;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${d.sym} analysis at ${d.asof}: price ${f0(k.price)} USDT, cycle score ${d.cycle} of 100 (${d.zone}), signal matrix, derivatives and sentiment.</h2>
<div class="row" style="justify-content:space-between;margin-bottom:12px"><div class="row"><span class="chip"><span class="dot" style="background:var(--up)"></span>Live · OKX</span><span class="chip">${d.inst}</span></div><span class="sub n">as of ${d.asof}</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(140px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">Last price</div><div class="v n">${f0(k.price)} <span class="sub">USDT</span></div><div class="sub n ${cl(k.chg24)}">${pc(k.chg24,2)} 24h</div></div>
<div class="card"><div class="lbl">24h range</div><div class="v2 n">${f0(k.lo24)}–${f0(k.hi24)}</div><div class="sub n">ATR14 ${f0(k.atr)} · ${(k.atr/k.price*100).toFixed(1)}% of price</div></div>
<div class="card"><div class="lbl">7d / 30d change</div><div class="v2 n"><span class="${cl(k.chg7)}">${pc(k.chg7)}</span> <span class="mu">/</span> <span class="${cl(k.chg30)}">${pc(k.chg30)}</span></div><div class="sub n">30d realized vol ${k.hv30.toFixed(0)}%</div></div>
<div class="card"><div class="lbl">Perp open interest</div><div class="v n">$${(k.oi/1e9).toFixed(2)}B</div><div class="sub n">funding ${(k.fr*100).toFixed(4)}% / 8h</div></div></div>
<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">Daily candles · ${d.K.length} days</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--bl)"></i>EMA20</span><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--am)"></i>SMA50</span><span class="row" style="gap:4px"><i style="width:14px;border-top:1px dashed var(--text-muted)"></i>BB 20,2</span><span class="row" style="gap:4px"><i style="width:14px;border-top:1px dashed var(--dn)"></i>S / R</span></span></div>${candles(d.K,d.L,d.DT,d.LV,k.price)}</div>
<div class="g" style="grid-template-columns:minmax(0,240px) minmax(0,1fr);margin:10px 0">
<div class="card" style="display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center"><div class="lbl" style="align-self:flex-start">Cycle temperature · 3-pillar composite</div>${gauge(d.cycle)}<div style="font-size:14px;font-weight:500;margin-top:4px">${d.zone}</div><div class="sub">${d.action}</div></div>
<div class="card"><div class="lbl" style="margin-bottom:10px">Pillars · 0 = cold, 100 = overheated</div>${d.pillars.map(p=>`<div style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span style="font-size:13px">${p[0]} <span class="mu">· ${p[1]}%</span></span><span class="n" style="font-size:14px;font-weight:500">${p[2]}</span></div><div style="height:8px;border-radius:4px;background:var(--surface-0);border:0.5px solid var(--border);overflow:hidden"><div style="height:100%;width:${p[2]}%;background:${p[2]<40?'var(--up)':p[2]>60?'var(--dn)':'var(--nt)'};border-radius:4px"></div></div><div class="sub n" style="margin-top:4px">${p[3]}</div></div>`).join('')}</div></div>
<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">Signal matrix · price-volume scoring per timeframe</span><span class="sub">weights 1D 50% · 4H 30% · 1H 20% → <b class="n" style="font-weight:500;color:var(--text-primary)">${m.total}/100</b></span></div>
<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px;table-layout:fixed"><colgroup><col style="width:88px"><col><col><col></colgroup><tr><th>Factor</th>${m.H.map(h=>`<th>${h}</th>`).join('')}</tr>${m.M.map(r=>`<tr><td style="color:var(--text-secondary)">${r[0]}</td>${r.slice(1).map(c=>`<td>${pill(c[0],c[1])}</td>`).join('')}</tr>`).join('')}<tr><td style="font-weight:500;border-top-color:var(--border-strong)">Score</td>${m.S.map(s=>`<td style="border-top-color:var(--border-strong)"><span class="n" style="font-weight:500">${s[0]}</span><span class="mu"> /100 · raw ${s[1]>0?'+':''}${s[1]}</span></td>`).join('')}</tr></table></div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin:10px 0">
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Funding rate · last 30 settlements</span><span class="n ${cl(k.fr)}" style="font-size:13px;font-weight:500">${(k.fr*100).toFixed(4)}%</span></div><div class="sub n" style="margin-bottom:6px">30-settlement avg ${dv.fravg.toFixed(4)}% · baseline 0.0100%</div>${bars(dv.F)}</div>
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Perp open interest · 30 days</span><span class="n" style="font-size:13px;font-weight:500">$${dv.OI[dv.OI.length-1].toFixed(2)}B</span></div><div class="sub n" style="margin-bottom:6px">1d <span class="${cl(dv.oi1d)}">${pc(dv.oi1d)}</span> · 30d <span class="${cl(dv.oi30d)}">${pc(dv.oi30d)}</span></div>${line(dv.OI,'var(--bl)')}</div>
<div class="card"><div class="row" style="justify-content:space-between"><span class="lbl">Top-trader long/short · 30 days</span><span class="n" style="font-size:13px;font-weight:500">${dv.lsr.toFixed(2)}</span></div><div class="sub n" style="margin-bottom:6px">long ${dv.longp}% · short ${100-dv.longp}% · 1.00 = balanced</div>${line(dv.LS,dv.lsr>1?'var(--up)':'var(--dn)',1)}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">
<div class="card"><div class="lbl">Options · ATM implied vol term structure</div><div class="sub n" style="margin-bottom:4px">front IV ${dv.IV[1].toFixed(0)}% vs HV30 ${k.hv30.toFixed(0)}% · 25d skew ${(dv.skew>0?'+':'')+dv.skew.toFixed(1)} vol (${dv.skew>0.5?'puts richer':dv.skew<-0.5?'calls richer':'flat'})</div>${ivcurve(dv.IV,dv.EX,k.hv30)}</div>
<div class="card"><div class="lbl">Options open interest · put / call</div><div class="v n" style="margin:4px 0 6px">${dv.pcr.toFixed(2)} <span class="sub">put/call ratio</span></div><div class="bar" style="height:12px"><div style="width:${dv.putp}%;background:var(--dn)"></div><div style="flex:1;background:var(--up)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:6px"><span>puts ${dv.putp}%</span><span>calls ${100-dv.putp}%</span></div>
<div class="lbl" style="margin-top:14px">Fear &amp; Greed · social sentiment (24h)</div><div class="row" style="gap:12px;margin-top:6px"><span class="n" style="font-size:26px;font-weight:500;color:${sn.fng<40?'var(--dn)':sn.fng>60?'var(--up)':'var(--nt)'}">${sn.fng}</span><span class="sub">${sn.fngLabel} · yesterday ${sn.fngPrev}</span></div>
<div class="bar" style="margin-top:8px"><div style="width:${sn.bull}%;background:var(--up)"></div><div style="width:${100-sn.bull-sn.bear}%;background:var(--nt)"></div><div style="flex:1;background:var(--dn)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:4px"><span>bullish ${sn.bull}%</span><span>neutral ${100-sn.bull-sn.bear}%</span><span>bearish ${sn.bear}%</span></div></div></div>`}

function conclusion(el,d){css();el.classList.add('atk');const t=d.tiles,ob=d.ob;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Conclusion: ${d.head}. Verdict ${t.verdict}, signal ${t.signal} of 100; entry ${f0(d.LV[2][0])}, stop ${f0(d.LV[3][0])}, targets ${f0(d.LV[1][0])} and ${f0(d.LV[0][0])}; options: ${d.opts.map(o=>o.kind).join(', ')}.</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Market direction · conclusion</div><div style="font-size:18px;font-weight:500;line-height:1.25;margin:4px 0 2px">${d.head}</div><div class="sub" style="margin-bottom:6px">${d.bias} · as of ${d.asof}</div>${d.evidence.map(e=>`<div class="ev"><span class="dot" style="background:${dotc(e[2])}"></span><span><span style="color:var(--text-secondary)">${e[0]} · </span>${e[1]}</span></div>`).join('')}</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(150px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">Verdict</div><div style="font-size:18px;font-weight:500;line-height:1.2;margin-top:2px">${t.verdict}</div><div class="sub">${t.passed} of 3 entry conditions met</div></div>
<div class="card"><div class="lbl">Long signal quality</div><div class="v n">${t.signal}<span class="sub"> /100</span> <span class="p" style="font-size:13px;font-weight:500;color:${t.gradeColor}">grade ${t.grade}</span></div><div class="sub n">${t.sub}</div></div>
<div class="card"><div class="lbl">Risk / reward</div><div class="v n">${t.rr1.toFixed(2)} <span class="sub">to T1</span></div><div class="sub n">${t.rr2.toFixed(2)} to T2 · risk ${f0(t.risk)} USDT per ${d.base}</div></div>
<div class="card"><div class="lbl">Sizing tier · cycle ${d.cycle}</div><div class="v n">≤ ${t.lever}</div><div class="sub">${t.size} of account per trade · stop ${t.stopw}</div></div></div>
<div class="g" style="grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);margin-bottom:10px">
<div class="card"><div class="lbl" style="margin-bottom:4px">Price ladder · USDT</div>${ladder(d.LV)}</div>
<div class="card"><div class="lbl" style="margin-bottom:2px">Entry conditions · all three required</div>${d.CK.map(c=>`<div style="display:flex;gap:10px;align-items:flex-start;padding:8px 0;border-top:0.5px solid var(--border)"><span style="flex:none;width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:${c[1]?'var(--ups)':'var(--dns)'};color:${c[1]?'var(--up)':'var(--dn)'};font-size:14px;font-weight:500">${c[1]?'✓':'✕'}</span><span><div style="font-size:13px;font-weight:500">${c[0]}</div><div class="sub n">${c[2]}</div></span></div>`).join('')}
<div class="lbl" style="margin-top:12px;margin-bottom:6px">Patterns &amp; divergences detected</div><div style="line-height:2">${d.PT.map(p=>`<span class="p ${p[1]=='u'?'u':p[1]=='d'?'d':''}">${p[0]}</span> `).join('')}</div>
<div class="lbl" style="margin-top:12px;margin-bottom:4px">Order book · top 50 levels</div><div class="bar"><div style="width:${ob.bidp}%;background:var(--up)"></div><div style="flex:1;background:var(--dn)"></div></div><div class="row sub n" style="justify-content:space-between;margin-top:4px"><span>bids ${f0(ob.bid)} ${d.base}</span><span>imbalance ${(ob.imb>0?'+':'')+ob.imb}%</span><span>asks ${f0(ob.ask)} ${d.base}</span></div></div></div>
<div class="lbl" style="margin:10px 0 6px 2px">Opening options · pick one, each button opens a preview (nothing is placed without confirmation)</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">${d.opts.map(o=>`<div class="card opt" style="${o.star?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span style="font-size:14px;font-weight:500"><span class="p" style="margin-right:6px">${o.tag}</span>${o.kind}</span>${o.star?'<span class="p u">best fit now</span>':''}</div><div class="sub">${o.fit}</div><div style="font-size:13px;line-height:1.45">${o.why}</div>${kv(o.rows)}<button data-cmd="${o.tag}">Preview option ${o.tag} ↗</button></div>`).join('')}</div>
<div class="sub" style="margin-top:10px">${d.foot}</div>`;
el.querySelectorAll('button[data-cmd]').forEach(b=>{const o=d.opts.find(x=>x.tag==b.dataset.cmd);b.onclick=()=>window.sendPrompt&&sendPrompt(`Preview option ${o.tag} (${o.kind}): \`${o.cmd}\`. Show me the preview and the exact risk in USDT — do NOT place it until I confirm.`)})}
/* ---- Dual Investment (DCD) buy-low advisory views ---- */
const pct=(x,d=1)=>(x*100).toFixed(d)+'%',spc=(x,d=1)=>(x>=0?'+':'')+(x*100).toFixed(d)+'%';
function votes(t){const S=t.signals,n=S.length,bw=(300-(n-1)*4)/n;let s='';S.forEach((g,i)=>{const c=g[3]<0?'var(--dn)':g[3]>0?'var(--up)':'var(--border-strong)';s+=`<rect x="${i*(bw+4)}" y="4" width="${bw}" height="24" rx="4" fill="${c}"><title>${g[0]} ${g[1]}: ${g[2]}</title></rect><text x="${i*(bw+4)+bw/2}" y="21" font-size="14" font-weight="500" text-anchor="middle" fill="${g[3]==0?'var(--text-muted)':'#fff'}">${g[3]<0?'↓':g[3]>0?'↑':'→'}</text>`});
s+=`<text x="0" y="46" font-size="11" fill="var(--dn)">${t.bear} bearish</text><text x="150" y="46" font-size="11" text-anchor="middle" fill="var(--text-muted)">${t.neut} neutral</text><text x="300" y="46" font-size="11" text-anchor="end" fill="var(--up)">${t.bull} bullish</text>`;
const px=(t.tilt+1)/2*300;s+=`<defs><linearGradient id="atkTilt" x1="0" x2="1"><stop offset="0" stop-color="var(--dn)"/><stop offset=".5" stop-color="var(--border-strong)"/><stop offset="1" stop-color="var(--up)"/></linearGradient></defs><rect x="0" y="68" width="300" height="8" rx="4" fill="url(#atkTilt)"/><rect x="${px-2}" y="62" width="4" height="20" rx="2" fill="var(--text-primary)"/><text x="${px}" y="58" font-size="11" font-weight="500" text-anchor="${px>250?'end':px<50?'start':'middle'}" fill="var(--text-primary)">tilt ${(t.tilt>=0?'+':'')+t.tilt.toFixed(2)}</text>`;
return `<svg width="100%" viewBox="0 0 300 86" role="img" aria-label="Technical vote strip, ${t.bear} bearish of ${S.length}" style="display:block;height:86px;overflow:visible">${s}</svg>`}
function ivbars(v){const cv=v.curve,m=Math.max(...cv.map(c=>c[2]),v.hv30)*1.25,Y=x=>84-(x/m)*66,bw=280/cv.length;let s='';cv.forEach((c,i)=>{const x=16+i*bw+bw*.15,w=bw*.7;s+=`<rect x="${x}" y="${Y(c[2])}" width="${w}" height="${84-Y(c[2])}" rx="3" fill="${i==0?'var(--am)':'var(--bl)'}"/><text x="${x+w/2}" y="${Y(c[2])+13}" font-size="10.5" font-weight="500" text-anchor="middle" fill="#fff">${(c[2]*100).toFixed(0)}%</text><text x="${x+w/2}" y="97" font-size="10" text-anchor="middle" fill="var(--text-muted)">${c[0]}</text>`});
s+=`<line x1="12" y1="${Y(v.hv30)}" x2="296" y2="${Y(v.hv30)}" stroke="var(--up)" stroke-width="1.5" stroke-dasharray="5 3"/><text x="296" y="${Y(v.hv30)-4}" font-size="10" text-anchor="end" fill="var(--up)">realized 30d ${(v.hv30*100).toFixed(0)}%</text>`;
return `<svg width="100%" viewBox="0 0 300 100" role="img" aria-label="Implied volatility by expiry" style="display:block;height:100px;overflow:visible">${s}</svg>`}
function evline(e,days){const X=d=>8+(d/days)*284,base=74,mb=Math.max(2,...e.list.map(x=>x[1]));let s='';for(let d=0;d<=days;d++)s+=`<line x1="${X(d)}" y1="26" x2="${X(d)}" y2="${base}" stroke="var(--border)"/><text x="${X(d)+2}" y="88" font-size="10" fill="var(--text-muted)">${d==0?'now':'D+'+d}</text>`;
s+=`<line x1="8" y1="${base}" x2="292" y2="${base}" stroke="var(--border-strong)"/>`;e.list.forEach(x=>{const h=8+(base-32)*x[1]/mb,px=X(Math.max(0,x[0]));s+=`<rect x="${px-4}" y="${base-h}" width="8" height="${h}" rx="3" fill="var(--am)"><title>${x[2]} · +${x[1].toFixed(2)}%</title></rect>`;if(x[1]>=1)s+=`<text x="${px+8}" y="${base-h/2+4}" font-size="11" font-weight="500" fill="var(--text-primary)">${x[2]}</text>`});
return `<svg width="100%" viewBox="0 0 300 92" role="img" aria-label="Macro events over the next ${days} days" style="display:block;height:92px;overflow:visible">${s}</svg>`}
function cone(c){const X0=54,X1=596,Y0=12,Y1=232,K=c.K,F=c.F,x0=K[0][0],x1=F[F.length-1][0]+6*36e5,X=t=>X0+(X1-X0)*(t-x0)/(x1-x0);
let lo=Math.min(...K.map(k=>k[3]),F[F.length-1][5],...c.strikes.map(s=>s[0])),hi=Math.max(...K.map(k=>k[2]),F[F.length-1][4]);const pd=(hi-lo)*.06;lo-=pd;hi+=pd;const Y=p=>Y1-(p-lo)/(hi-lo)*(Y1-Y0);let s='';
for(let t=Math.ceil(lo/1000)*1000;t<hi;t+=1000)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="var(--border)"/><text x="${X0-6}" y="${Y(t)+4}" font-size="11" text-anchor="end" fill="var(--text-muted)">${f0(t)}</text>`;
const day=864e5;for(let t=Math.ceil(x0/day)*day;t<=x1;t+=day){const d=new Date(t);s+=`<text x="${X(t)}" y="${Y1+16}" font-size="10.5" text-anchor="middle" fill="var(--text-muted)">${d.toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</text>`}
s+=`<line x1="${X(c.now)}" y1="${Y0}" x2="${X(c.now)}" y2="${Y1}" stroke="var(--text-muted)" stroke-dasharray="3 4"/><text x="${X(c.now)+4}" y="${Y0+10}" font-size="10.5" fill="var(--text-muted)">now</text>`;
const P=[[c.now,c.spot,c.spot],...F.map(f=>[f[0],f[1],f[2]])],E=[[c.now,c.spot,c.spot],...F.map(f=>[f[0],f[3],f[4]])];
s+=`<polygon points="${P.map(p=>X(p[0])+','+Y(p[2])).join(' ')} ${[...P].reverse().map(p=>X(p[0])+','+Y(p[1])).join(' ')}" fill="var(--bl)" opacity=".14"/><polygon points="${P.map(p=>X(p[0])+','+Y(p[2])).join(' ')} ${[...P].reverse().map(p=>X(p[0])+','+Y(p[1])).join(' ')}" fill="none" stroke="var(--bl)"/>`;
s+=`<polyline fill="none" stroke="var(--bl)" stroke-width="2" stroke-dasharray="7 5" points="${E.map(p=>X(p[0])+','+Y(p[1])).join(' ')}"/><polyline fill="none" stroke="var(--bl)" stroke-width="2" stroke-dasharray="7 5" points="${E.map(p=>X(p[0])+','+Y(p[2])).join(' ')}"/>`;
const bw=Math.max(2,(X(K[1][0])-X(K[0][0]))*.6);K.forEach(k=>{const col=k[4]>=k[1]?'var(--up)':'var(--dn)',x=X(k[0]);s+=`<line x1="${x}" y1="${Y(k[2])}" x2="${x}" y2="${Y(k[3])}" stroke="${col}"/><rect x="${x-bw/2}" y="${Y(Math.max(k[1],k[4]))}" width="${bw}" height="${Math.max(1,Math.abs(Y(k[1])-Y(k[4])))}" fill="${col}"/>`});
c.events.forEach(e=>{const h=5+e[1]*9,x=X(e[0]);s+=`<rect x="${x-3}" y="${Y1-h}" width="6" height="${h}" rx="2" fill="var(--am)"><title>${e[2]}</title></rect>`});
c.strikes.forEach((st,i)=>{const y=Y(st[0]);s+=`<line x1="${X(c.now)}" y1="${y}" x2="${X(st[1])}" y2="${y}" stroke="var(--up)" stroke-width="${st[3]?3:2}" ${st[3]?'':'stroke-dasharray="5 4"'}/><circle cx="${X(st[1])}" cy="${y}" r="4.5" fill="var(--up)" stroke="var(--surface-2)" stroke-width="1.5"/><text x="${X(st[1])+8}" y="${y+4}" font-size="11" font-weight="500" fill="var(--text-primary)">${st[2]}</text>`});
const L=F[F.length-1];s+=`<text x="${X(L[0])+8}" y="${Y(L[3])+4}" font-size="11" fill="var(--bl)">${f0(L[3])} floor</text><text x="${X(L[0])+8}" y="${Y(L[4])+4}" font-size="11" fill="var(--bl)">${f0(L[4])} cap</text><rect x="${X(c.now)-64}" y="${Y(c.spot)-9}" width="60" height="18" rx="4" fill="var(--text-primary)"/><text x="${X(c.now)-34}" y="${Y(c.spot)+4}" font-size="11" font-weight="500" text-anchor="middle" fill="var(--surface-2)">${f0(c.spot)}</text>`;
return `<svg width="100%" viewBox="0 0 680 256" role="img" aria-label="Price cone for the next 7 days with recommended strikes" style="display:block;overflow:visible">${s}</svg>`}
function wf(w){const steps=w.steps,lo=Math.min(...steps.map(x=>x[1]))-300,hi=Math.max(...steps.map(x=>x[1]))+300,Y=v=>16+(hi-v)/(hi-lo)*150,n=steps.length,cw=300/n;let s='';
steps.forEach((x,i)=>{const cx=i*cw+cw/2,y=Y(x[1]),prev=i?Y(steps[i-1][1]):y;if(i)s+=`<line x1="${cx-cw/2}" y1="${prev}" x2="${cx-cw/2+cw*.18}" y2="${prev}" stroke="var(--border-strong)"/><rect x="${cx-10}" y="${Math.min(prev,y)}" width="20" height="${Math.max(2,Math.abs(y-prev))}" rx="3" fill="${x[1]<steps[i-1][1]?'var(--am)':'var(--up)'}"/>`;
s+=`<line x1="${cx-cw/2+cw*.18}" y1="${y}" x2="${cx+cw/2-cw*.18}" y2="${y}" stroke="${i==n-1?'var(--bl)':'var(--text-muted)'}" stroke-width="${i==n-1?2.5:1.5}"/><text x="${cx}" y="${y-6}" font-size="11" font-weight="500" text-anchor="middle" fill="var(--text-primary)">${f0(x[1])}</text>`;
if(i)s+=`<text x="${cx}" y="${Math.max(prev,y)+14}" font-size="10.5" text-anchor="middle" fill="${x[1]<steps[i-1][1]?'var(--am)':'var(--up)'}">${x[1]-steps[i-1][1]>=0?'+':'−'}${f0(Math.abs(x[1]-steps[i-1][1]))}</text>`;
s+=`<text x="${cx}" y="186" font-size="10.5" text-anchor="middle" fill="var(--text-muted)">${x[0]}</text>`});
return `<div class="lbl" style="margin-bottom:2px">${w.title}</div><svg width="100%" viewBox="0 0 300 192" role="img" aria-label="${w.title}" style="display:block;overflow:visible">${s}</svg><div class="sub" style="margin-top:4px">${w.note}</div>`}
function dcdAnalysis(el,d){css();el.classList.add('atk');const t=d.tech,v=d.vol,e=d.ev,F=d.cone.F;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">BTC buy-low Dual Investment analysis at ${d.asof}: spot ${f0(d.spot)}, technical tilt ${t.tilt.toFixed(2)}, 7-day implied vol ${pct(v.iv7,0)}, ${e.count} US macro events, 7-day price floor ${f0(F[F.length-1][3])}.</h2>
<div class="row" style="justify-content:space-between;margin-bottom:12px"><div class="row"><span class="chip"><span class="dot" style="background:var(--up)"></span>Live · OKX</span><span class="chip">BTC-USDT Dual Investment · buy low · USDT deposit</span></div><span class="sub n">as of ${d.asof}</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(140px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">BTC spot</div><div class="v n">${f0(d.spot)}</div><div class="sub n ${cl(d.chg24)}">${spc(d.chg24,2)} 24h · ${f0(d.lo24)}–${f0(d.hi24)}</div></div>
<div class="card"><div class="lbl">Technical tilt</div><div class="v n ${t.tilt<-.25?'dn':t.tilt>.25?'up':''}">${(t.tilt>=0?'+':'')+t.tilt.toFixed(2)}</div><div class="sub n">${t.bear} of ${t.signals.length} signals bearish · range shifted ${spc(t.drift7)}</div></div>
<div class="card"><div class="lbl">Implied vol · 7d / 1d</div><div class="v n">${pct(v.iv7,0)} <span class="sub">/ ${pct(v.iv1,0)}</span></div><div class="sub n">typical 7-day move ±${pct(v.move7,1)} · realized 30d ${pct(v.hv30,0)}</div></div>
<div class="card"><div class="lbl">${e.fedHours!=null?'FOMC decision':'US macro events'}</div><div class="v n">${e.fedHours!=null?e.fedHours.toFixed(1)+' h':e.count}</div><div class="sub n">${e.fedHours!=null?`consensus ${e.fedFc} vs ${e.fedPrev} · ${e.count} events in window`:'importance 3 only, next 7 days'}</div></div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin-bottom:10px">
<div class="card"><div class="lbl">Which way is BTC leaning?</div><div class="v2 n">${t.bear} of ${t.signals.length} <span class="sub">signals bearish</span></div>${votes(t)}<div class="sub" style="margin-top:6px">${spc(t.drift7)} range tilt · ${spc(d.spot/t.ema200-1)} vs 200-day avg: a pullback inside an uptrend</div></div>
<div class="card"><div class="lbl">How big can the swings be?</div><div class="v2 n">±${pct(v.move7,1)} <span class="sub">typical 7-day move</span></div>${ivbars(v)}<div class="sub" style="margin-top:6px">Front expiry ${pct(v.curve[0][2],0)} vs ${pct(v.iv7,0)} for the week: tomorrow is the riskiest day</div></div>
<div class="card"><div class="lbl">What could break the range?</div><div class="v2 n">${e.fedHours!=null?e.fedHours.toFixed(1)+' h <span class="sub">to the FOMC decision</span>':e.count+' <span class="sub">important US events</span>'}</div>${evline(e,7)}<div class="sub" style="margin-top:6px">Each event adds a cushion before settlement: −${f0(e.cushion1)} USDT on day 1</div></div></div>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span style="font-size:14px;font-weight:500">Where BTC can trade over the next 7 days · 90 % confidence</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:14px;height:8px;background:var(--bl);opacity:.25"></i>options-implied</span><span class="row" style="gap:4px"><i style="width:14px;border-top:2px dashed var(--bl)"></i>with event cushion</span><span class="row" style="gap:4px"><i style="width:14px;height:2px;background:var(--up)"></i>recommended strikes</span><span class="row" style="gap:4px"><i style="width:6px;height:8px;background:var(--am)"></i>macro event</span></span></div>${cone(d.cone)}</div>
<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">How the signals shape the forecast</span><span class="sub">each vote moves the range · votes → tilt → floor</span></div><div class="g" style="grid-template-columns:minmax(0,1.25fr) minmax(0,1fr)"><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><tr><th>Signal</th><th>TF</th><th class="n">Value</th><th>Vote</th></tr>${t.signals.map(g=>`<tr><td>${g[0]}<div class="mu" style="font-size:11px">${g[4]||""}</div></td><td class="mu">${g[1]}</td><td class="n">${g[2]}</td><td><span class="p ${g[3]<0?"d":g[3]>0?"u":""}">${g[3]<0?"↓ bearish":g[3]>0?"↑ bullish":"→ neutral"}</span></td></tr>`).join("")}</table></div><div>${wf(d.wf)}</div></div></div>`}
function dcdConclusion(el,d){css();el.classList.add('atk');const N=d.notional;
const card=t=>{const p=t.pick;if(!p)return `<div class="card opt"><span class="p">${t.name}</span><div style="font-size:14px;font-weight:500;margin-top:6px">Nothing clears the ≤ ${pct(t.thr,0)} bar this week</div><div class="sub">Stay in flexible savings until the FOMC decision has passed, then re-check.</div></div>`;
return `<div class="card opt" style="${t.house?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span class="p ${t.house?'u':''}" style="font-weight:500">${t.name}${t.house?' · house pick':''}</span>${p.fallback?'<span class="p d">closest available</span>':''}</div><div class="sub n" style="word-break:break-all">${p.productId}</div><div class="row" style="align-items:baseline;gap:10px"><span class="v n" style="font-size:28px">${pct(p.apy,1)}</span><span class="sub n">APY · ${pct(p.absYield,3)} over ${p.days.toFixed(1)} d</span></div>${kv([['Strike',`${f0(p.strike)} <span class="mu">−${pct(p.distance,1)}</span>`],['Settles',p.expDate+' 16:00 UTC+8'],['Chance of conversion',`<span class="${p.pEx<=.1?'up':p.pEx<=.2?'':'dn'}" style="font-weight:500">${pct(p.pEx,0)}</span> <span class="mu">${pct(p.pExIv,0)} on options alone</span>`],['Floor that day',f0(p.floor)],['BTC above strike',`${(N*(1+p.absYield)).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} USDT`],['BTC at or below',`${(N/p.strike*(1+p.absYield)).toFixed(5)} BTC`]])}<div><div class="lbl" style="margin-bottom:3px">Reason</div><div style="font-size:12.5px;line-height:1.45;color:var(--text-secondary)">${p.reason.map(w=>'· '+w).join('<br>')}</div></div><button data-tier="${t.key}">Subscribe ${f0(N)} USDT · ${t.name} ↗</button></div>`};
const S=d.shelf,tierBg={conservative:'var(--ups)',balanced:'rgba(42,120,214,.16)',aggressive:'rgba(237,161,0,.2)',avoid:'var(--surface-0)'};
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Recommendation: ${d.head}. ${d.tiers.filter(t=>t.pick).map(t=>`${t.name}: ${t.pick.productId} at ${pct(t.pick.apy,1)} APY, ${pct(t.pick.pEx,0)} conversion chance`).join('; ')}.</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Our read · conclusion</div><div style="font-size:18px;font-weight:500;line-height:1.25;margin:4px 0 2px">${d.head}</div><div class="sub" style="margin-bottom:6px">${d.bias} · as of ${d.asof}</div>${d.evidence.map(e=>`<div class="ev"><span class="dot" style="background:${dotc(e[2])}"></span><span><span style="color:var(--text-secondary)">${e[0]} · </span>${e[1]}</span></div>`).join('')}</div>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:6px"><span style="font-size:14px;font-weight:500">Every product on the shelf · APY and chance of conversion</span><span class="row sub"><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:var(--ups)"></i>≤ 5 %</span><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:rgba(42,120,214,.16)"></i>≤ 10 %</span><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:rgba(237,161,0,.2)"></i>≤ 20 %</span><span class="row" style="gap:4px"><i style="width:12px;height:12px;border-radius:3px;background:var(--surface-0);border:0.5px solid var(--border)"></i>not recommended</span></span></div>
<div style="overflow-x:auto"><table style="width:100%;border-collapse:separate;border-spacing:3px;font-size:11px"><tr><th style="text-align:right;border:0">strike ↓ · settles →</th>${S.exps.map(x=>`<th style="text-align:center;border:0">${x[1]}<br><span class="n mu" style="font-weight:400">floor ${f0(x[2])}</span></th>`).join('')}</tr>${S.strikes.map(k=>`<tr><td class="n" style="text-align:right;border:0;font-weight:500;white-space:nowrap">${f0(k)} <span class="mu" style="font-weight:400">−${((1-k/d.spot)*100).toFixed(1)}%</span></td>${S.exps.map(x=>{const c=S.cells[x[0]+'|'+Math.round(k)];if(!c)return '<td style="border:0;text-align:center;color:var(--text-muted)">·</td>';return `<td style="border:0;text-align:center;border-radius:5px;padding:4px 2px;background:${tierBg[c[2]]};${c[3]?'outline:1.5px solid var(--text-primary);':''}${c[2]=='avoid'?'color:var(--text-muted)':''}"><span class="n" style="font-weight:500;font-size:12px">${pct(c[0],1)}</span><br><span class="n" style="font-size:10.5px">${pct(c[1],0)}${c[3]?' · '+c[3]:''}</span></td>`}).join('')}</tr>`).join('')}</table></div><div class="sub" style="margin-top:6px">Cell = reference APY over the chance that BTC settles at or below the strike (event-adjusted). Outlined cells are the picks below.</div></div>
<div class="lbl" style="margin:0 0 6px 2px">Recommendation by risk profile · ${f0(N)} USDT · each button asks for a quote (nothing is placed without confirmation)</div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin-bottom:10px">${d.tiers.map(card).join('')}</div>
<div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-tier]').forEach(b=>{const t=d.tiers.find(x=>x.key==b.dataset.tier);b.onclick=()=>window.sendPrompt&&sendPrompt(`Put ${f0(N)} USDT into the ${t.name.toLowerCase()} pick from your report (${t.pick.productId}).`)})}
/* ---------- sentiment radar (scenario 3) ---------- */
const RCSS=`.atk .rc{display:flex;flex-direction:column;gap:9px}.atk .rc h4{margin:0;font-size:11px;font-weight:500;letter-spacing:.04em;text-transform:uppercase;color:var(--text-muted)}
.atk .fl{display:flex;gap:8px;font-size:12.5px;line-height:1.4;color:var(--text-secondary)}.atk .fl .dot{margin-top:5px;flex:none}
.atk .lk{display:block;font-size:12.5px;line-height:1.35;color:var(--bl);text-decoration:none;padding:3px 0}.atk .lk:hover{text-decoration:underline}.atk .lk span{color:var(--text-muted)}
.atk .vd{font-size:12px;font-weight:500;padding:3px 10px;border-radius:999px;white-space:nowrap}.atk .vd.vw{background:var(--ups);color:var(--up)}.atk .vd.vr{background:var(--dns);color:var(--dn)}.atk .vd.vn{background:var(--surface-0);color:var(--text-secondary)}
.atk .big{font-size:18px;font-weight:500;line-height:1.25;margin:4px 0 2px}.atk .rt td,.atk .rt th{font-size:12.5px;padding:6px 6px}.atk .rt td.n,.atk .rt th.n{text-align:right}`;
function rcss(){css();if(!document.getElementById('atk-rcss')){const s=document.createElement('style');s.id='atk-rcss';s.textContent=RCSS;document.head.appendChild(s)}}
const fdot=k=>k=='r'?'var(--dn)':k=='a'?'var(--am)':'var(--up)',sg=(x,d=1)=>(x>0?'+':x<0?'−':'')+Math.abs(x).toFixed(d)+'%',esc=t=>String(t).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const vpill=(k,t)=>`<span class="vd ${k==1?'vw':k==2?'vr':'vn'}">${t||(k==1?'Worth watching':k==2?'Too risky to chase':'Context')}</span>`;
function radarMap(P,thrX,thrY){const X0=52,X1=664,Y0=26,Y1=318,lx=v=>Math.log2(Math.min(8,Math.max(.4,v))),xa=lx(.4),xb=lx(8);
const ys=P.map(p=>p[2]),lo=Math.max(-40,Math.min(-15,...ys)-4),hi=Math.min(60,Math.max(25,...ys)+6),X=v=>X0+(lx(v)-xa)/(xb-xa)*(X1-X0),Y=v=>Y1-(Math.min(hi,Math.max(lo,v))-lo)/(hi-lo)*(Y1-Y0),vm=Math.max(...P.map(p=>p[3]))||1;
let s=`<rect x="${X(thrX)}" y="${Y0}" width="${X1-X(thrX)}" height="${Y(thrY)-Y0}" fill="var(--ups)" opacity=".55"/><text x="${X1-6}" y="${Y0+15}" text-anchor="end" font-size="12" font-weight="500" fill="var(--text-secondary)">attention and leverage arriving together</text>`;
[.5,1,2,4,8].forEach(t=>{s+=`<line x1="${X(t)}" y1="${Y0}" x2="${X(t)}" y2="${Y1}" stroke="var(--border)"/><text x="${X(t)}" y="${Y1+16}" font-size="12" text-anchor="middle" fill="var(--text-muted)">${t}×</text>`});
for(let t=Math.ceil(lo/10)*10;t<=hi;t+=10)s+=`<line x1="${X0}" y1="${Y(t)}" x2="${X1}" y2="${Y(t)}" stroke="${t==0?'var(--border-strong)':'var(--border)'}"/><text x="${X0-6}" y="${Y(t)+4}" font-size="12" text-anchor="end" fill="var(--text-muted)">${t>0?'+':''}${t}%</text>`;
s+=`<line x1="${X(thrX)}" y1="${Y0}" x2="${X(thrX)}" y2="${Y1}" stroke="var(--text-muted)" stroke-dasharray="4 3"/><line x1="${X0}" y1="${Y(thrY)}" x2="${X1}" y2="${Y(thrY)}" stroke="var(--text-muted)" stroke-dasharray="4 3"/>`;
const used=[];P.slice().sort((a,b)=>a[4]-b[4]||b[3]-a[3]).forEach(p=>{const x=X(p[1]),y=Y(p[2]),r=4+Math.sqrt(p[3]/vm)*15,c=p[4]==1?'var(--up)':p[4]==2?'var(--dn)':p[4]==3?'var(--am)':'var(--nt)';
s+=`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r.toFixed(1)}" fill="${c}" fill-opacity="${p[4]?.3:.16}" stroke="${c}" stroke-width="${p[4]?1.5:.75}" stroke-opacity="${p[4]?1:.5}"><title>${p[0]} · attention ${p[1].toFixed(1)}× its weekly norm (${f0(p[8])} mentions) · open interest ${sg(p[2])} in 24h, ${sg(p[6])} in 4h, ${sg(p[5])} in 1h · price ${sg(p[7])}</title></circle>`;
if(p[4]){let ly=y+4,left=x>X1-70;for(let k=0;k<6&&used.some(u=>Math.abs(u[0]-x)<64&&Math.abs(u[1]-ly)<14);k++)ly+=14;used.push([x,ly]);s+=`<text x="${left?x-r-5:x+r+5}" y="${ly}" font-size="13" font-weight="500" text-anchor="${left?'end':'start'}" fill="var(--text-primary)" stroke="var(--surface-2)" stroke-width="3" paint-order="stroke">${p[0]}</text>`}
else if(Math.abs(p[2])>=12||p[1]>=2.2)s+=`<text x="${x+r+4}" y="${y+4}" font-size="11" fill="var(--text-muted)">${p[0]}</text>`});
s+=`<text x="${(X0+X1)/2}" y="${Y1+34}" font-size="12" text-anchor="middle" fill="var(--text-secondary)">Attention · mentions in the last 24h vs the coin's own weekly norm →</text><text transform="translate(13 ${(Y0+Y1)/2}) rotate(-90)" font-size="12" text-anchor="middle" fill="var(--text-secondary)">Open interest · 24h change →</text>`;
return `<svg width="100%" viewBox="0 0 680 356" role="img" aria-label="Attention versus open-interest change for every alt perpetual scanned" style="display:block">${s}</svg>`}
function radarScan(el,d){rcss();el.classList.add('atk');
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Sentiment radar · alt perpetuals on OKX · as of ${d.asof}</div><div class="big">${d.head}</div><div class="sub">${d.sub}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(140px,1fr));margin-bottom:10px">${d.kpi.map(k=>`<div class="card"><div class="lbl">${k[0]}</div><div class="v n" style="font-size:26px;margin-top:2px">${k[1]}</div><div class="sub">${k[2]}</div></div>`).join('')}</div>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;margin-bottom:4px"><span style="font-size:14px;font-weight:500">Where attention and leverage are moving</span><span class="row sub"><span class="row" style="gap:4px"><span class="dot" style="background:var(--up)"></span>worth watching</span><span class="row" style="gap:4px"><span class="dot" style="background:var(--dn)"></span>too risky to chase</span><span class="row" style="gap:4px"><span class="dot" style="background:var(--nt)"></span>rest of the market</span><span>bubble = 24h volume</span></span></div>${radarMap(d.pts,d.thrX,d.thrY)}</div>
${d.themes.length?`<div class="row" style="margin-bottom:10px"><span class="lbl">Narratives in play</span>${d.themes.map(t=>`<span class="chip"><b style="font-weight:500;color:var(--text-primary)">${t[0]}</b>${t[1].join(' · ')}</span>`).join('')}</div>`:''}
<div class="card"><div style="overflow-x:auto"><table class="rt" style="width:100%;border-collapse:collapse"><tr><th>Coin</th><th>Narrative</th><th class="n">Attention</th><th class="n">Mentions 24h</th><th class="n">OI 24h</th><th class="n">OI 4h</th><th class="n">Price 24h</th><th class="n">Volume vs norm</th><th class="n">Read</th></tr>${d.rows.map(r=>`<tr><td style="font-weight:500">${r[0]}</td><td class="mu">${r[1]}</td><td class="n" style="font-weight:500">${r[2].toFixed(1)}×</td><td class="n">${f0(r[3])}</td><td class="n ${cl(r[4])}">${sg(r[4])}</td><td class="n ${cl(r[5])}">${sg(r[5])}</td><td class="n ${cl(r[6])}">${sg(r[6])}</td><td class="n">${r[7].toFixed(1)}×</td><td class="n">${vpill(r[8])}</td></tr>`).join('')}</table></div><div class="sub" style="margin-top:6px">${d.note}</div></div>`}
function duo(a,b){const W=300,H=74,f=(arr,y0,y1)=>{const lo=Math.min(...arr),hi=Math.max(...arr),rg=hi-lo||1;return arr.map((v,i)=>(2+i/(arr.length-1)*(W-4)).toFixed(1)+','+(y1-(v-lo)/rg*(y1-y0)).toFixed(1)).join(' ')};
return `<svg width="100%" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="48-hour price with open interest underneath" style="display:block;height:${H}px">${a.length>1?`<polyline fill="none" stroke="var(--text-primary)" stroke-width="1.8" vector-effect="non-scaling-stroke" stroke-linejoin="round" points="${f(a,4,40)}"/>`:''}${b.length>1?`<polyline fill="none" stroke="var(--bl)" stroke-width="1.8" vector-effect="non-scaling-stroke" stroke-linejoin="round" points="${f(b,48,72)}"/>`:''}</svg>`}
function radarCandidates(el,d){rcss();el.classList.add('atk');
const fl=a=>a.map(x=>`<div class="fl"><span class="dot" style="background:${fdot(x[0])}"></span><span>${x[1]}</span></div>`).join('');
const card=c=>`<div class="card rc" style="${c.k==1?'border:1.5px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span class="row" style="gap:8px"><span style="font-size:20px;font-weight:500">${c.ccy}</span><span class="chip">${c.theme}</span></span>${vpill(c.k)}</div>
<div class="row" style="align-items:baseline;gap:10px"><span class="v n">${c.lastS}</span><span class="n ${cl(c.chg24)}" style="font-size:14px;font-weight:500">${sg(c.chg24)}</span><span class="sub">24h</span></div>
<div style="font-size:13.5px;line-height:1.45;font-weight:500">${c.why}</div>
<div><h4>What is driving it</h4><div style="font-size:13px;line-height:1.45;margin-top:3px">${c.driver}</div></div>
<div><h4>Do price and volume support it</h4><div class="g" style="grid-template-columns:repeat(4,1fr);gap:6px;margin:5px 0">${c.stats.map(s=>`<div><div class="lbl" style="font-size:11px">${s[0]}</div><div class="n ${s[2]||''}" style="font-size:15px;font-weight:500">${s[1]}</div></div>`).join('')}</div>${duo(c.px,c.oi)}<div class="row sub" style="gap:12px;font-size:11px"><span class="row" style="gap:4px"><i style="width:12px;height:2px;background:var(--text-primary)"></i>price · 48h</span><span class="row" style="gap:4px"><i style="width:12px;height:2px;background:var(--bl)"></i>open interest</span></div><div class="fl" style="margin-top:4px"><span class="dot" style="background:${dotc(c.confK)}"></span><span>${c.conf}</span></div></div>
<div><h4>Crowded positioning</h4>${fl(c.crowd)}</div><div><h4>Liquidity</h4>${fl(c.liq)}</div>
<div><h4>Read more</h4>${c.links.map(l=>`<a class="lk" href="${esc(l[1])}" target="_blank" rel="noopener">${esc(l[0])} <span>· ${esc(l[2])} ↗</span></a>`).join('')}</div>
${c.k==1?`<button data-ccy="${c.ccy}" style="margin-top:auto">Design a position plan for ${c.ccy} ↗</button>`:''}</div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Our read · candidates · as of ${d.asof}</div><div class="big">${d.head}</div><div class="sub">${d.bias}</div></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));margin-bottom:10px">${d.cards.map(card).join('')}</div><div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-ccy]').forEach(b=>b.onclick=()=>window.sendPrompt&&sendPrompt(`Design a position plan for ${b.dataset.ccy}.`))}
function radarPlan(el,d){rcss();el.classList.add('atk');const m=50+d.score/2;
const tier=t=>`<div class="card opt" style="${t.house?'border:2px solid var(--up)':''}"><div class="row" style="justify-content:space-between"><span class="p ${t.house?'u':''}" style="font-weight:500">${t.name}${t.house?' · house pick':''}</span><span class="sub">${t.fit}</span></div>
<div class="row" style="align-items:baseline;gap:8px"><span class="v n" style="font-size:18px">${t.entry}</span><span class="sub">${t.entryNote}</span></div>
${kv([['Stop',`<span class="dn" style="font-weight:500">${t.stop}</span> <span class="mu">${t.stopPct}</span>`],['Take profit 1 · half',`<span class="up" style="font-weight:500">${t.tp1}</span> <span class="mu">${t.tp1Pct}</span>`],['Take profit 2 · half',`<span class="up" style="font-weight:500">${t.tp2}</span> <span class="mu">${t.tp2Pct}</span>`],['Position',`${t.notional} USDT <span class="mu">${t.contracts}</span>`],['Margin · leverage',`${t.margin} USDT · ${t.lever}×`],['Loss at the stop',`<span class="dn">−${t.loss} USDT</span> <span class="mu">${t.lossPct} of account</span>`],['Gain at both targets',`<span class="up">+${t.gain} USDT</span>`],['Reward to risk',`1 : ${t.rr}`]])}
<div style="font-size:12.5px;line-height:1.45;color:var(--text-secondary)">${t.why}</div><button data-tier="${t.key}">Place the ${t.name.toLowerCase()} plan on the demo account ↗</button></div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="lbl">Position plan · ${d.instId} · as of ${d.asof}</div><div class="big">${d.head}</div><div class="sub">${d.bias}</div></div>
<div class="g" style="grid-template-columns:minmax(0,1.6fr) minmax(0,1fr);margin-bottom:10px"><div class="card"><div class="row" style="justify-content:space-between;align-items:baseline"><span style="font-size:14px;font-weight:500">Signal scorecard</span><span><span class="v n ${cl(d.score)}" style="font-size:26px">${d.score>0?'+':''}${d.score}</span> <span class="sub">${d.scoreLabel}</span></span></div>
<div style="position:relative;height:10px;border-radius:5px;margin:10px 0 4px;background:linear-gradient(90deg,var(--dn) 0,var(--dns) 35%,var(--surface-0) 35%,var(--surface-0) 65%,var(--ups) 65%,var(--up) 100%)"><span style="position:absolute;left:calc(${m}% - 2px);top:-4px;width:4px;height:18px;border-radius:2px;background:var(--text-primary)"></span></div><div class="row sub" style="justify-content:space-between;font-size:11px"><span>−100 short</span><span>−30</span><span>wait</span><span>+30</span><span>long +100</span></div>
<table class="rt" style="width:100%;border-collapse:collapse;margin-top:8px"><tr><th>Signal</th><th>Reading</th><th class="n">Weight</th><th class="n">Points</th></tr>${d.signals.map(s=>`<tr><td style="font-weight:500;white-space:nowrap">${s[0]}</td><td style="color:var(--text-secondary)">${s[1]}</td><td class="n mu">${s[2]}</td><td class="n"><span class="p ${s[3]>0?'u':s[3]<0?'d':''}">${s[3]>0?'+':''}${s[3]}</span></td></tr>`).join('')}</table></div>
<div class="card rc"><div class="row" style="justify-content:space-between;align-items:baseline"><span style="font-size:14px;font-weight:500">Risk</span><span><span class="v n" style="font-size:26px">${d.risk}</span> <span class="sub">of 10</span></span></div><div class="bar">${Array.from({length:10},(_,i)=>`<span style="flex:1;background:${i<d.risk?(d.risk>=7?'var(--dn)':d.risk>=4?'var(--am)':'var(--up)'):'var(--surface-0)'}"></span>`).join('')}</div>
${d.risks.map(r=>`<div class="fl"><span class="dot" style="background:var(--am)"></span><span>${r}</span></div>`).join('')}<div><h4>Plan is wrong if</h4><div style="font-size:13px;line-height:1.45;margin-top:3px">${d.invalid}</div></div><div>${kv(d.levels)}</div></div></div>
<div class="lbl" style="margin:0 0 6px 2px">${d.tiersLabel}</div><div class="g" style="grid-template-columns:repeat(auto-fit,minmax(215px,1fr));margin-bottom:10px">${d.tiers.map(tier).join('')}</div><div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-tier]').forEach(b=>{const t=d.tiers.find(x=>x.key==b.dataset.tier);b.onclick=()=>window.sendPrompt&&sendPrompt(`Place the ${t.name.toLowerCase()} ${d.ccy} plan on the demo account.`)})}
function tapeRow(t){const C={L:'var(--up)',C:'var(--ups)',S:'var(--dn)',X:'var(--dns)',N:'var(--surface-0)'},T={L:'price up, OI up — longs opening',C:'price up, OI down — shorts covering',S:'price down, OI up — shorts opening',X:'price down, OI down — longs closing',N:'quiet hour'};
return `<div style="display:flex;gap:2px" role="img" aria-label="Hour-by-hour positioning, last 24 hours">${t.split('').map((k,i)=>`<span title="${t.length-i}h ago · ${T[k]}" style="flex:1;height:12px;border-radius:2px;background:${C[k]};${k=='C'?'box-shadow:inset 0 0 0 1px var(--up)':k=='X'?'box-shadow:inset 0 0 0 1px var(--dn)':''}"></span>`).join('')}</div>`}
function tfGrid(tf){const bg=(v,vol)=>{const a=vol?Math.min(1,Math.max(0,(v-1)/3)):Math.min(1,Math.abs(v)/12);return vol?`rgba(42,120,214,${(.06+a*.3).toFixed(2)})`:v>=0?`rgba(15,157,106,${(.06+a*.34).toFixed(2)})`:`rgba(224,51,76,${(.06+a*.34).toFixed(2)})`};
return `<table style="width:100%;border-collapse:separate;border-spacing:3px;font-size:12px"><tr><th style="border:0;padding:0"></th>${['1h','4h','24h'].map(h=>`<th style="border:0;padding:0 0 1px;text-align:center;font-size:11px">${h}</th>`).join('')}</tr>${tf.map((r,i)=>`<tr><td style="border:0;padding:0 4px 0 0;color:var(--text-muted);font-size:11px;white-space:nowrap">${r[0]}</td>${r.slice(1).map(v=>`<td class="n" style="border:0;text-align:center;border-radius:5px;padding:5px 2px;font-weight:500;background:${bg(v,i==2)}">${i==2?v.toFixed(1)+'×':sg(v)}</td>`).join('')}</tr>`).join('')}</table>`}
function meter(m){const c=m[2]=='r'?'var(--dn)':m[2]=='a'?'var(--am)':m[2]=='g'?'var(--up)':'var(--nt)';
return `<div><div class="row" style="justify-content:space-between;gap:4px;flex-wrap:nowrap"><span class="lbl" style="font-size:11px;white-space:nowrap">${m[0]}</span><span class="n" style="font-size:12px;font-weight:500;color:${m[2]=='r'?'var(--dn)':'var(--text-primary)'};white-space:nowrap">${m[1]}</span></div><div style="position:relative;height:4px;border-radius:2px;background:var(--surface-0);margin-top:4px">${m[3]==null?'':`<span style="position:absolute;left:calc(${(m[3]*100).toFixed(0)}% - 4px);top:-3px;width:8px;height:10px;border-radius:3px;background:${c}"></span>`}</div></div>`}
function duoLv(a,b,lv){const W=300,H=112,X0=40,X1=258,T=20,B=108,lo=Math.min(...a,lv.go,lv.stop),hi=Math.max(...a,lv.go,lv.stop),rg=hi-lo||1,Y=v=>T+(hi-v)/rg*(B-T),ol=Math.min(...b),oh=Math.max(...b),og=(oh-ol)||1,YO=v=>B-(v-ol)/og*(B-T)*.85,X=i=>X0+i/(a.length-1)*(X1-X0),gc=lv.side=='short'?'var(--dn)':lv.side=='long'?'var(--up)':'var(--text-muted)';
const fmt=v=>v>=1000?Math.round(v).toLocaleString('en-US'):v>=10?v.toFixed(2):v>=.01?v.toFixed(4):v.toPrecision(3),fo=v=>v>=1000?'$'+(v/1000).toFixed(2)+'B':'$'+Math.round(v)+'M';
let s=`<text x="${X0}" y="11" font-size="10.5" fill="var(--text-secondary)"><tspan fill="var(--bl)" font-weight="500">▮</tspan> Open interest (left)   <tspan fill="var(--am)" font-weight="500">━</tspan> Price (right) · 3 days</text>`;
[0,.5,1].forEach(t=>{const v=ol+og*t,y=YO(v);s+=`<line x1="${X0}" y1="${y.toFixed(1)}" x2="${X1}" y2="${y.toFixed(1)}" stroke="var(--border)"/><text x="${X0-3}" y="${(y+3).toFixed(1)}" font-size="9.5" text-anchor="end" fill="var(--bl)">${fo(v)}</text>`});
[0,.5,1].forEach(t=>{const v=lo+rg*t;s+=`<text x="${X1+3}" y="${(Y(v)+3).toFixed(1)}" font-size="9.5" fill="var(--am)">${fmt(v)}</text>`});
const bp=b.map((v,i)=>X(i*(a.length-1)/(b.length-1)).toFixed(1)+','+YO(v).toFixed(1)).join(' ');
s+=`<polygon fill="var(--bl)" opacity=".14" points="${X0},${B} ${bp} ${X1},${B}"/><polyline fill="none" stroke="var(--bl)" stroke-width="1.5" stroke-linejoin="round" points="${bp}"/>`;
s+=`<line x1="${X0}" y1="${Y(lv.go).toFixed(1)}" x2="${X1}" y2="${Y(lv.go).toFixed(1)}" stroke="${gc}" stroke-width="1.3" stroke-dasharray="5 3"/><line x1="${X0}" y1="${Y(lv.stop).toFixed(1)}" x2="${X1}" y2="${Y(lv.stop).toFixed(1)}" stroke="var(--text-muted)" stroke-width="1" stroke-dasharray="2 3"/>`;
s+=`<polyline fill="none" stroke="var(--am)" stroke-width="1.8" stroke-linejoin="round" points="${a.map((v,i)=>X(i).toFixed(1)+','+Y(v).toFixed(1)).join(' ')}"/>`;
return `<svg width="100%" viewBox="0 0 ${W} ${H}" role="img" aria-label="Open interest (left axis) and price (right axis) over the last three days, with the entry-trigger and setup-fails levels" style="display:block">${s}</svg>`}
function radar(el,d){rcss();el.classList.add('atk');
const SP={1:['vw','Long setup'],2:['vr','Short setup'],3:['vn','No trade']},ar=s=>s>0?'<span class="up">▲</span>':s<0?'<span class="dn">▼</span>':'<span class="mu">·</span>';
const smBar=m=>{if(!m)return `<div class="row" style="justify-content:space-between"><span class="lbl" style="font-size:11px">Smart money</span><span class="sub">no position among the top 100</span></div>`;const t=m.l+m.s||1;
return `<div><div class="row" style="justify-content:space-between;flex-wrap:nowrap"><span class="lbl" style="font-size:11px">Smart money</span><span class="n" style="font-size:13px;font-weight:500">${m.net}</span></div><div style="display:flex;height:16px;border-radius:4px;overflow:hidden;gap:2px;margin:4px 0 3px"><span class="n" style="width:${(m.l/t*100).toFixed(0)}%;min-width:44px;background:var(--ups);color:var(--up);font-size:11px;line-height:16px;padding:0 5px;white-space:nowrap">${m.lS} long</span><span class="n" style="flex:1;min-width:48px;background:var(--dns);color:var(--dn);font-size:11px;line-height:16px;padding:0 5px;text-align:right;white-space:nowrap">${m.sS} short</span></div><div class="sub" style="font-size:11px">${m.sub}</div></div>`};
const card=c=>`<div class="card rc" style="gap:10px;${c.k==1?'border:1.5px solid var(--up)':c.k==2?'border:1.5px solid var(--dn)':''}"><div class="row" style="justify-content:space-between;flex-wrap:nowrap"><span class="row" style="gap:6px"><span style="font-size:20px;font-weight:500">${c.ccy}</span><span class="chip">${c.theme}</span></span><span class="vd ${SP[c.k][0]}">${SP[c.k][1]}${c.k<3?' · '+c.conv:''}</span></div>
<div class="row" style="justify-content:space-between;align-items:baseline"><span class="row" style="align-items:baseline;gap:8px"><span class="v n">${c.lastS}</span><span class="n ${cl(c.chg24)}" style="font-size:14px;font-weight:500">${sg(c.chg24)}</span></span><span class="p">${c.stage}</span></div>
<div style="font-size:13.5px;line-height:1.35;font-weight:500">${c.tag}</div>
<div class="g" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:6px">${c.abs.map(a=>`<div style="background:var(--surface-0);border-radius:8px;padding:6px 8px;min-width:0"><div class="lbl" style="font-size:11px;white-space:nowrap">${a[0]}</div><div class="n" style="font-size:15px;font-weight:500;white-space:nowrap">${a[1]}</div><div class="sub n" style="font-size:11px;white-space:nowrap">${a[2]}</div>${a[3]&&a[3].length>1?`<div title="Mentions per 4 hours, last 48 hours" style="display:flex;align-items:flex-end;gap:1.5px;height:16px;margin-top:4px">${a[3].map((v,i,A)=>`<span style="flex:1;border-radius:1px;background:var(--bl);opacity:${i>=A.length-2?1:.45};height:${Math.max(8,v/Math.max(...A,1)*100).toFixed(0)}%"></span>`).join('')}</div>`:''}</div>`).join('')}</div>
<div>${duoLv(c.px,c.oi,c.lv)}<div class="row n" style="justify-content:space-between;font-size:12px;margin-top:5px">${c.lv.side=='long'?`<span><span class="up" style="font-weight:500">Enter long above ${c.lv.goS}</span></span><span class="mu">setup fails below ${c.lv.stopS}</span>`:c.lv.side=='short'?`<span><span class="dn" style="font-weight:500">Enter short below ${c.lv.goS}</span></span><span class="mu">setup fails above ${c.lv.stopS}</span>`:`<span class="mu">12h range ${c.lv.stopS} – ${c.lv.goS}</span>`}</div></div>
${tfGrid(c.tf)}
${c.pos?`<div><div class="lbl" style="font-size:11px;margin-bottom:4px">Who is long · who is short</div>${c.pos.map(r=>`<div style="margin-bottom:6px"><div class="row" style="justify-content:space-between;flex-wrap:nowrap;gap:6px;font-size:11.5px"><span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${r[0]}</span><span class="n mu" style="white-space:nowrap">${r[2]}</span></div>${r[1]==null?'':`<div style="display:flex;height:14px;border-radius:4px;overflow:hidden;gap:2px;margin-top:3px"><span class="n" style="width:${r[1]}%;min-width:30px;background:var(--ups);color:var(--up);font-size:11px;line-height:14px;padding:0 5px">${r[1]}%</span><span class="n" style="flex:1;min-width:30px;background:var(--dns);color:var(--dn);font-size:11px;line-height:14px;padding:0 5px;text-align:right">${100-r[1]}%</span></div>`}</div>`).join('')}</div>`:smBar(c.sm)}
<div><div class="lbl" style="font-size:11px;margin-bottom:2px">Evidence · ▲ votes long · ▼ votes short</div><div class="g" style="grid-template-columns:minmax(0,1fr);gap:0">${c.ev.map(e=>`<div class="row" style="justify-content:space-between;flex-wrap:nowrap;gap:6px;font-size:12px;padding:2px 0"><span style="white-space:nowrap">${ar(e[2])} ${e[0]}</span><span class="n mu" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${e[1]}</span></div>`).join('')}</div></div>
<div style="font-size:12.5px;line-height:1.4;color:var(--text-secondary)">${c.driver}</div>${c.note?`<div class="row" style="gap:6px;font-size:12px;padding:5px 8px;border-radius:6px;background:rgba(237,161,0,.14)"><span class="dot" style="background:var(--am)"></span><span>${c.note}</span></div>`:''}${d.plan?`<button data-ccy="${c.ccy}" style="margin-top:auto">Design a position for ${c.ccy} ↗</button>`:''}</div>`;
const lg=(c,t,b)=>`<span class="row" style="gap:4px"><i style="width:12px;height:10px;border-radius:2px;background:${c};${b?'box-shadow:inset 0 0 0 1px '+b:''}"></i>${t}</span>`,dt=(c,t)=>`<span class="row" style="gap:4px"><span class="dot" style="background:${c}"></span>${t}</span>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">${esc(d.head)}</h2>
<div class="card" style="margin-bottom:10px"><div class="row" style="justify-content:space-between;align-items:baseline;margin-bottom:8px"><span class="big" style="margin:0">${d.head}</span><span class="lbl">${d.scanned} alt perpetuals scanned on OKX · as of ${d.asof}</span></div>
<div class="row sub" style="margin-bottom:2px">${dt('var(--up)','long setup')}${dt('var(--dn)','short setup')}${dt('var(--am)','no trade')}${dt('var(--nt)','rest of the market')}<span>bubble = 24h volume</span></div>${radarMap(d.pts,d.thrX,d.thrY)}</div>
<div class="row sub" style="margin:0 2px 8px;gap:10px"><span style="color:var(--text-primary);font-weight:500">Candidates</span><span class="row" style="gap:4px"><i style="width:12px;height:0;border-top:1.5px dashed var(--text-secondary)"></i>entry trigger</span><span class="row" style="gap:4px"><i style="width:12px;height:0;border-top:1px dotted var(--text-muted)"></i>setup fails</span></div>
<div class="g" style="grid-template-columns:repeat(auto-fit,minmax(290px,1fr));margin-bottom:10px">${d.cards.map(card).join('')}</div>${d.passed&&d.passed.length?`<div class="card" style="margin-bottom:10px;padding:10px 16px"><div class="row" style="gap:6px 14px"><span class="lbl">Checked and passed over</span>${d.passed.map(x=>`<span style="font-size:12.5px"><span class="dot" style="background:var(--am);margin-right:5px"></span><b style="font-weight:500">${x[0]}</b> <span class="mu">${x[1]}</span></span>`).join('')}</div></div>`:''}<div class="sub">${d.foot}</div>`;
el.querySelectorAll('button[data-ccy]').forEach(b=>b.onclick=()=>window.sendPrompt&&sendPrompt(`Design a position for ${b.dataset.ccy}.`))}
function positionCard(el,d){rcss();el.classList.add('atk');const L=d.side=='long',c=L?'var(--up)':'var(--dn)',
row=(k,v,sub,cls)=>`<div style="display:flex;justify-content:space-between;align-items:baseline;gap:12px;padding:9px 0;border-top:0.5px solid var(--border)"><span style="font-size:13px;color:var(--text-secondary);white-space:nowrap">${k}</span><span style="text-align:right"><span class="n ${cls||''}" style="font-size:17px;font-weight:500">${v}</span>${sub?` <span class="n mu" style="font-size:12px;white-space:nowrap">${sub}</span>`:''}</span></div>`;
el.innerHTML=`<h2 style="position:absolute;left:-9999px">Recommended ${d.ccy} ${d.side} position: entry ${d.entry}, stop ${d.stop}, targets ${d.tp1} and ${d.tp2}, ${d.contracts} contracts at ${d.lever}x</h2>
<div class="card" style="max-width:460px;margin:0 auto;border:1.5px solid ${c};padding:16px 18px"><div class="row" style="justify-content:space-between;flex-wrap:nowrap"><span class="row" style="gap:8px"><span style="font-size:22px;font-weight:500">${d.ccy}</span><span class="vd ${L?'vw':'vr'}" style="font-size:13px">${L?'Long':'Short'} · ${d.lever}× isolated</span></span><span class="sub n">conviction ${d.conv}</span></div>
<div class="sub n" style="margin:2px 0 8px">${d.instId} · price ${d.last} · as of ${d.asof}</div>
${row('Entry',d.entry,d.entryNote)}${row('Take profit 1 · half',d.tp1,d.tp1Pct,'up')}${row('Take profit 2 · half',d.tp2,d.tp2Pct,'up')}${row('Stop loss',d.stop,d.stopPct,'dn')}${row('Size',d.contracts+' contracts','≈ '+d.notional+' USDT · margin '+d.margin)}
<div class="g" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin:10px 0 12px">${[['Risk at stop','−'+d.loss+' USDT',d.lossPct+' of '+d.balance,'dn'],['Gain at targets','+'+d.gain+' USDT','both filled','up'],['Reward : risk',d.rr+' : 1','blended','']].map(a=>`<div style="background:var(--surface-0);border-radius:8px;padding:7px 9px;min-width:0"><div class="lbl" style="font-size:11px;white-space:nowrap">${a[0]}</div><div class="n ${a[3]}" style="font-size:15px;font-weight:500;white-space:nowrap">${a[1]}</div><div class="sub n" style="font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${a[2]}</div></div>`).join('')}</div>
<button data-go="1" style="width:100%;padding:11px;font-size:15px;font-weight:500">Confirm order ↗</button>
<details style="margin-top:10px"><summary style="cursor:pointer;font-size:12.5px;color:var(--text-secondary)">How these numbers were set</summary><div style="margin-top:6px">${d.notes.map(n=>`<div class="fl" style="padding:2px 0"><span style="flex:none;width:68px;color:var(--text-muted)">${n[0]}</span><span>${n[1]}</span></div>`).join('')}</div></details></div>`;
el.querySelector('button[data-go]').onclick=()=>window.sendPrompt&&sendPrompt(`Confirm — place the ${d.ccy} ${d.side} on the demo account.`)}
window.ATK={analysis,conclusion,dcdAnalysis,dcdConclusion,radarScan,radarCandidates,radarPlan,radar,positionCard,version:'1.8.1'};

})();
